# <font color= MediumSpringGreen> Análise - Carreira Analista de dados - State of Data 2019,2021,2022</font>

## <font color= MediumSpringGreen> Projeto </font>

Como forma de analisar a carreira de "analista de dados" irei explorar algumas informações sobre as características destes profissionais, verificando através de tabelas de frequência.


## <font color= MediumSpringGreen> Importando bibliotecas </font>

In [236]:
!pip install wget
import wget

Defaulting to user installation because normal site-packages is not writeable


Importarei as bibliotecas necessárias, configuradas no "requirements.txt" do projeto.



*   pandas==1.3.5
*   plotly==5.5.0



In [237]:
wget.download('https://raw.githubusercontent.com/FranciscoFoz/analista-de-dados-state-of-data-2021/main/requirements.txt', 'requirements.txt')

!pip install -r requirements.txt


Defaulting to user installation because normal site-packages is not writeable


In [238]:
import pandas as pd
import plotly.express as px



pd.options.display.max_columns = 400

## <font color= MediumSpringGreen> Importando dados </font>

### 2019

In [239]:
url = 'https://github.com/FranciscoFoz/state-of-data-2019-2021-2022/raw/main/Datasets/2019/datahackers-survey-2019-anonymous-responses.csv'
df_state_of_data_2019 = pd.read_csv(url)

### 2021

In [240]:
url = 'https://raw.githubusercontent.com/FranciscoFoz/state-of-data-2019-2021-2022/main/Datasets/2021/State%20of%20Data%202021%20-%20Dataset%20-%20Pgina1.csv'
df_state_of_data_2021 = pd.read_csv(url,low_memory=False)

### 2022

In [241]:
url = 'https://raw.githubusercontent.com/FranciscoFoz/state-of-data-2019-2021-2022/main/Datasets/2022/State_of_data_2022.csv'
df_state_of_data_2022 = pd.read_csv(url,low_memory=False)

## <font color= MediumSpringGreen> Funções </font>

In [242]:
import funcoes as f

# <font color= MediumSpringGreen> 2019 </font>

### <font color= MediumSpringGreen> Preparação inicial dos dados </font>

### <font color= MediumSpringGreen> Verificando duplicatas </font>

In [243]:
df_state_of_data_2019.duplicated().sum()

0

### <font color= MediumSpringGreen> Selecionando dados </font>

In [244]:
df_state_of_data_2019.head()

('P0', 'id')  ('P1', 'age') ('P2', 'gender')  \
0  v9otv8j9wdvjrv9otvwnn9owhzq54ktv           37.0        Masculino   
1  875ul998t0hqcv0871uptwf3oswcfv35           24.0         Feminino   
2  puscuk079vw1pusbb900pzw2xvpxtgdk           26.0        Masculino   
3  rmel8ewqpbffp2mnfbzermel8eqincov           21.0        Masculino   
4  pj9mgud4d6mdct1l7vq0pj9mgu78h6ju           27.0        Masculino   

   ('P3', 'living_in_brasil') ('P5', 'living_state')  \
0                           1      Minas Gerais (MG)   
1                           1         São Paulo (SP)   
2                           1         São Paulo (SP)   
3                           1         São Paulo (SP)   
4                           1                    NaN   

   ('P6', 'born_or_graduated') ('P8', 'degreee_level')  \
0                          1.0  Estudante de Graduação   
1                          1.0  Estudante de Graduação   
2                          1.0   Graduação/Bacharelado   
3                          0.0  Estudante de Graduação   
4                          1.0   Graduação/Bacharelado   

  ('P10', 'job_situation') ('P12', 'workers_number')  ('P13', 'manager')  \
0          Empregado (CTL)                  de 1 a 5                 0.0   
1          Empregado (CTL)             Acima de 3000                 0.0   
2          Empregado (CTL)             Acima de 3000                 0.0   
3               Estagiário                de 11 a 50                 0.0   
4               Freelancer                 de 6 a 10                 1.0   

          ('P16', 'salary_range') ('P17', 'time_experience_data_science')  \
0  de R$ 1.001/mês a R$ 2.000/mês  Não tenho experiência na área de dados   
1   de R$ 2.001/mês a R$ 3000/mês                          Menos de 1 ano   
2  de R$ 4.001/mês a R$ 6.000/mês                           de 1 a 2 anos   
3  de R$ 1.001/mês a R$ 2.000/mês                          Menos de 1 ano   
4  de R$ 6.001/mês a R$ 8.000/mês                           de 4 a 5 anos   

                   ('P18', 'time_experience_before')  \
0  Não tive experiência na área de TI/Engenharia ...   
1  Não tive experiência na área de TI/Engenharia ...   
2                                     de 6 a 10 anos   
3                                      de 2 a 3 anos   
4                                      de 4 a 5 anos   

   ('P19', 'is_data_science_professional')  ('P20', 'linear_regression')  \
0                                        0                             0   
1                                        1                             0   
2                                        1                             0   
3                                        1                             0   
4                                        1                             1   

   ('P20', 'logistic_regression')  ('P20', 'glms')  ('P20', 'decision_tree')  \
0                               0                0                         0   
1                               0                0                         0   
2                               0                0                         0   
3                               0                0                         0   
4                               0                0                         1   

   ('P20', 'random_forest')  ('P20', 'neural_networks')  \
0                         0                           0   
1                         0                           0   
2                         1                           1   
3                         1                           0   
4                         1                           0   

   ('P20', 'bayesian_inference')  ('P20', 'ensemble')  ('P20', 'svms')  \
0                              0                    0                0   
1                              0                    0                0   
2                              0                    1                1   
3                              0                    0           

In [245]:
# Seleção de colunas necessárias
df_state_of_data_2019_filtrado = df_state_of_data_2019.loc[:,[
    "('D6', 'anonymized_role')",
    "('D4', 'anonymized_market_sector')",
    "('P10', 'job_situation')",
    "('P16', 'salary_range')",
    "('P18', 'time_experience_before')",
    "('P17', 'time_experience_data_science')",
    "('P21', 'sql_')",
    "('P21', 'r')",
    "('P21', 'python')",
    "('P21', 'c_c++_c#')",
    "('P21', 'dotnet')",
    "('P21', 'java')",
    "('P21', 'julia')",
    "('P21', 'sas_stata')",
    "('P21', 'visual_basic_vba')",
    "('P21', 'scala')",
    "('P21', 'matlab')",
    "('P21', 'php')",
    "('P21', 'no_listed_languages')",
    "('P23', 'sql')",
    "('P23', 'nosql')",
    "('P23', 'images')",
    "('P23', 'nlp')",
    "('P23', 'videos')",
    "('P23', 'sheets')",
    "('P23', 'other')",
    "('P24', 'sql')",
    "('P24', 'nosql')",
    "('P24', 'imagens')",
    "('P24', 'nlp')",
    "('P24', 'vídeos')",
    "('P24', 'planilhas')",
    "('P24', 'other')",
    "('P25', 'aws')",
    "('P25', 'gcp')",
    "('P25', 'azure')",
    "('P25', 'ibm')",
    "('P25', 'on_premise_servers')",
    "('P25', 'cloud_própria')",
    "('P25', 'other')",
    "('P26', 'mysql')",
    "('P26', 'oracle')",
    "('P26', 'sql_server')",
    "('P26', 'aurora')",
    "('P26', 'dynamodb')",
    "('P26', 'coachdb')",
    "('P26', 'cassandra')",
    "('P26', 'mongodb')",
    "('P26', 'mariadb')",
    "('P26', 'datomic')",
    "('P26', 's3')",
    "('P26', 'postgresql')",
    "('P26', 'elaticsearch')",
    "('P26', 'db2')",
    "('P26', 'ms_access')",
    "('P26', 'sqlite')",
    "('P26', 'sybase')",
    "('P26', 'firebase')",
    "('P26', 'vertica')",
    "('P26', 'redis')",
    "('P26', 'neo4j')",
    "('P26', 'google_bigtable')",
    "('P26', 'hbase')",
    "('P26', 'other')",
    "('P27', 'microsoft_powerbi')",
    "('P27', 'qlik_view_qlik_sense')",
    "('P27', 'tableau')",
    "('P27', 'metabase')",
    "('P27', 'superset')",
    "('P27', 'redash')",
    "('P27', 'microstrategy')",
    "('P27', 'ibm_analytics_cognos')",
    "('P27', 'sap_business_objects')",
    "('P27', 'oracle_business_intelligence')",
    "('P27', 'birst')",
    "('P27', 'looker')",
    "('P27', 'google_data_studio')",
    "('P27', 'only_excel_gsheets')",
    "('P27', 'no_bi_tool_at_work')",
    "('P27', 'other')",
    "('P28', 'sql_&_stored_procedures')",
    "('P28', 'apache_airflow')",
    "('P28', 'luigi')",
    "('P28', 'aws_glue')",
    "('P28', 'talend')",
    "('P28', 'pentaho')",
    "('P28', 'alteryx')",
    "('P28', 'oracle_data_integrator')",
    "('P28', 'ibm_data_stage')",
    "('P28', 'sap_bw_etl')",
    "('P28', 'siss_sql_server_integration_services')",
    "('P28', 'other')"]]

In [246]:
#Filtro analista de dados
df_state_of_data_2019_filtrado = df_state_of_data_2019_filtrado[df_state_of_data_2019_filtrado["('D6', 'anonymized_role')"] == 'Data Analyst/Analista de Dados']

#Filtro de situação de trabalho
situacao_trabalho = ['Empregado (CTL)','Freelancer','Empreendedor ou Empregado (CNPJ)','Servidor Público']

df_state_of_data_2019_filtrado = df_state_of_data_2019_filtrado[df_state_of_data_2019_filtrado["('P10', 'job_situation')"]\
                                    .isin(situacao_trabalho)]

In [247]:
#Alterando nomenclatura da faixa salarial
faixa_salarial = {
    'de R$ 6.001/mês a R$ 8.000/mês' : 'de 6 à 8 mil reais/mês',
    'de R$ 4.001/mês a R$ 6.000/mês' : 'de 4 à 6 mil reais/mês',
    'de R$ 8.001/mês a R$ 12.000/mês': 'de 8 à 12 mil reais/mês',
    'de R$ 3.001/mês a R$ 4.000/mês': 'de 3 à 4 mil reais/mês',
    'de R$ 2.001/mês a R$ 3000/mês': 'de 2 à 3 mil reais/mês',
    'de R$ 12.001/mês a R$ 16.000/mês': 'de 12 à 16 mil reais/mês',
    'de R$ 1.001/mês a R$ 2.000/mês': 'de 1 à 2 mil reais/mês',
    'de R$ 20.001/mês a R$ 25.000/mês':'de 20 à 25 mil reais/mês',
    'Acima de R$ 25.001/mês': 'acima de 25 mil reais/mês',
    'de R$ 16.001/mês a R$ 20.000/mês':'de 16 à 20 mil reais/mês'
}

df_state_of_data_2019_filtrado.loc[:,"('P16', 'salary_range')"] = df_state_of_data_2019_filtrado.loc[:,"('P16', 'salary_range')"].map(faixa_salarial)

In [248]:
df_state_of_data_2019_filtrado

('D6', 'anonymized_role') ('D4', 'anonymized_market_sector')  \
1     Data Analyst/Analista de Dados                           Educação   
16    Data Analyst/Analista de Dados                             Varejo   
31    Data Analyst/Analista de Dados                             Outras   
48    Data Analyst/Analista de Dados     Tecnologia/Fábrica de Software   
90    Data Analyst/Analista de Dados             Indústria (Manufatura)   
...                              ...                                ...   
1729  Data Analyst/Analista de Dados                 Finanças ou Bancos   
1731  Data Analyst/Analista de Dados                 Internet/Ecommerce   
1739  Data Analyst/Analista de Dados     Tecnologia/Fábrica de Software   
1749  Data Analyst/Analista de Dados                             Outras   
1755  Data Analyst/Analista de Dados                    Telecomunicação   

              ('P10', 'job_situation')  ('P16', 'salary_range')  \
1                      Empregado (CTL)   de 2 à 3 mil reais/mês   
16                     Empregado (CTL)  de 8 à 12 mil reais/mês   
31                     Empregado (CTL)   de 3 à 4 mil reais/mês   
48                     Empregado (CTL)   de 3 à 4 mil reais/mês   
90                     Empregado (CTL)   de 3 à 4 mil reais/mês   
...                                ...                      ...   
1729                   Empregado (CTL)   de 3 à 4 mil reais/mês   
1731                   Empregado (CTL)   de 6 à 8 mil reais/mês   
1739  Empreendedor ou Empregado (CNPJ)   de 1 à 2 mil reais/mês   
1749                   Empregado (CTL)   de 4 à 6 mil reais/mês   
1755                   Empregado (CTL)   de 3 à 4 mil reais/mês   

                      ('P18', 'time_experience_before')  \
1     Não tive experiência na área de TI/Engenharia ...   
16                                      Mais de 10 anos   
31                                       Menos de 1 ano   
48                                        de 1 a 2 anos   
90    Não tive experiência na área de TI/Engenharia ...   
...                                                 ...   
1729                                     Menos de 1 ano   
1731  Não tive experiência na área de TI/Engenharia ...   
1739                                     Menos de 1 ano   
1749                                      de 1 a 2 anos   
1755                                     de 6 a 10 anos   

     ('P17', 'time_experience_data_science')  ('P21', 'sql_')  ('P21', 'r')  \
1                             Menos de 1 ano                1             0   
16                             de 2 a 3 anos                1             0   
31                            Menos de 1 ano                0             0   
48                            Menos de 1 ano                0             0   
90                             de 1 a 2 anos                0             1   
...                                      ...              ...           ...   
1729                           de 1 a 2 anos                1             1   
1731                          de 6 a 10 anos                1             0   
1739                          Menos de 1 ano                0             0   
1749                           de 1 a 2 anos                0             0   
1755                          Menos de 1 ano                1             0   

      ('P21', 'python')  ('P21', 'c_c++_c#')  ('P21', 'dotnet')  \
1                     1                    0                  0   
16                    1                    0                  0   
31                    0                    0                  0   
48                    0                    0                  0   
90                    1                    1                  0   
...                 ...                  ...                ...   
1729                  1                    0                  0   
1731                  1                    0                  0   
1739                  0                    0

## <font color= MediumSpringGreen> Análise dos dados </font>

### <font color= MediumSpringGreen> Total da amostra </font>

In [249]:
quantidade_amostra_total = len(df_state_of_data_2019_filtrado)


print(f'A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de {quantidade_amostra_total}.\nEssa pesquisa não questionou se estes profissionais trabalhavam no Brasil ou no exterior.')

A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de 149.
Essa pesquisa não questionou se estes profissionais trabalhavam no Brasil ou no exterior.


### <font color= MediumSpringGreen> Atuação profissional </font>

Nesta pesquisa, não foi questionado a atuação profissional.

#### <font color= MediumSpringGreen> Setor </font>

In [250]:
 f.tabela_frequencia(df_state_of_data_2019_filtrado,"('D4', 'anonymized_market_sector')")

anonymized_market_sector     %
0   Tecnologia/Fábrica de Software  26.2
1               Finanças ou Bancos  16.8
2                           Outras   9.4
3               Internet/Ecommerce   7.4
4                         Educação   6.7
5                        Marketing   6.0
6                    Setor Público   5.4
7                           Varejo   4.7
8           Indústria (Manufatura)   4.7
9                  Telecomunicação   3.4
10                   Área da Saúde   2.7
11                Setor Automotivo   2.0
12      Entretenimento ou Esportes   2.0
13                    Agronegócios   1.3
14               Setor Alimentício   0.7
15          Seguros ou Previdência   0.7

Os setores que mais empregam analistas de dados é o de Tecnologia/Fábrica de Software (26.2%) e o de Finanças ou Bancos	(16.8%).

#### <font color= MediumSpringGreen> Nível </font>

Nesta pesquisa não foi questionado o nível de senioridade dos participantes.

#### <font color= MediumSpringGreen> Situação de trabalho </font>

In [251]:
 f.tabela_frequencia(df_state_of_data_2019_filtrado,"('P10', 'job_situation')")

job_situation     %
0                   Empregado (CTL)  89.3
1  Empreendedor ou Empregado (CNPJ)   5.4
2                  Servidor Público   3.4
3                        Freelancer   2.0

A maior parte dos profissionais (89.3%) atuam de forma CLT. 

#### <font color= MediumSpringGreen> Faixa salarial </font>

In [252]:
f.tabela_frequencia(df_state_of_data_2019_filtrado,"('P16', 'salary_range')")


salary_range     %
0    de 4 à 6 mil reais/mês  30.9
1    de 3 à 4 mil reais/mês  27.5
2   de 8 à 12 mil reais/mês  13.4
3    de 6 à 8 mil reais/mês  12.1
4    de 2 à 3 mil reais/mês  10.7
5    de 1 à 2 mil reais/mês   3.4
6  de 12 à 16 mil reais/mês   1.3
7  de 16 à 20 mil reais/mês   0.7

A faixa salarial geral majoritária do cargo está entre 3 e 6 mil reais.

#### <font color= MediumSpringGreen> Tempo de experiência </font>

In [253]:
f.tabela_frequencia(df_state_of_data_2019_filtrado,"('P18', 'time_experience_before')")

time_experience_before     %
0  Não tive experiência na área de TI/Engenharia ...  29.5
1                                     Menos de 1 ano  23.5
2                                      de 1 a 2 anos  14.1
3                                      de 2 a 3 anos  10.7
4                                     de 6 a 10 anos  10.1
5                                      de 4 a 5 anos  10.1
6                                    Mais de 10 anos   2.0

Um terço dos profissionais (29,5%) não tiveram uma experiência na área de tecnologia antes de atuar no cargo.

In [254]:
f.tabela_frequencia(df_state_of_data_2019_filtrado,"('P17', 'time_experience_data_science')")

time_experience_data_science     %
0                           de 1 a 2 anos  24.8
1                          Menos de 1 ano  22.8
2                           de 2 a 3 anos  20.1
3                           de 4 a 5 anos  15.4
4                          de 6 a 10 anos  12.1
5                         Mais de 10 anos   4.0
6  Não tenho experiência na área de dados   0.7

Metade dos profissionais tiveram entrada recente na área de dados, entre menos de 1 ano até 2 anos.

#### <font color= MediumSpringGreen> Ferramentas </font>

##### <font color= MediumSpringGreen> **Quais das fontes de dados listadas você já analisou ou processou no trabalho?** </font>

In [255]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,[19,20,21,22,23,24,25],'fontes_dados')

fontes_dados     %
0          sql  38.4
1       sheets  35.5
2        nosql  12.3
3          nlp  10.3
4       images   2.3
5        other   1.3
6       videos   0.0

##### <font color= MediumSpringGreen> **Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?** </font>

In [256]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,[26,27,28,29,30,31,32],'fontes_dados_mais_utilizadas')

fontes_dados_mais_utilizadas     %
0                          sql  58.6
1                    planilhas  32.3
2                        nosql   6.5
3                          nlp   2.7
4                      imagens   0.0
5                       vídeos   0.0
6                        other   0.0

Dentre as fontes processadas e mais utilizadas pelos profissionais estão os bancos de dados relacionais (SQL) e as planilhas (sheets). 

##### <font color= MediumSpringGreen> **Quais das linguagens listadas abaixo você utiliza no trabalho?**
 </font>

In [257]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,[6,7,8,9,10,11,12,13,14,15,16,17,18],'linguagens_utilizadas')

linguagens_utilizadas     %
0                   sql_  35.7
1                 python  32.1
2                      r  11.0
3       visual_basic_vba   4.9
4              sas_stata   3.6
5                    php   3.2
6               c_c++_c#   2.6
7                   java   2.6
8                  scala   1.6
9                 matlab   1.6
10                dotnet   0.6
11                 julia   0.3
12   no_listed_languages   0.0

Dentre as linguagens, lideram o SQL e Python, mas  R e VBA estão entre as próximas.

##### <font color= MediumSpringGreen> **Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?**
 </font>

Nao foi considerada essa questão para a análise, devido a ela ter sido mascarada, portanto pode não refletir a quantidade correta.

##### <font color= MediumSpringGreen> **Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?**
 </font>

In [258]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,
                                         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
                                          57, 58, 59, 60, 61, 62, 63],
                                         'SGBD')

SGBD     %
0        postgresql  17.6
1             mysql  15.8
2        sql_server  15.8
3            oracle   8.8
4                s3   8.5
5           mongodb   6.0
6            sqlite   3.9
7         ms_access   3.2
8             other   3.2
9           mariadb   2.8
10           aurora   2.5
11         firebase   2.1
12  google_bigtable   2.1
13            redis   1.8
14              db2   1.4
15         dynamodb   1.1
16     elaticsearch   1.1
17           sybase   0.7
18          vertica   0.7
19          datomic   0.4
20        cassandra   0.4
21            hbase   0.4
22          coachdb   0.0
23            neo4j   0.0

O banco de dados com maior uso entre os profissionais é o PostgreSQL, em seguida o MySQL e o SQL Server.

##### <font color= MediumSpringGreen> **Quais das opções de Cloud listadas abaixo você utiliza no trabalho?**
 </font>

In [259]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,[33,34,35,36,37,38,39],'cloud')

cloud     %
0                 aws  36.9
1                 gcp  17.3
2       cloud_própria  17.3
3               azure  14.3
4  on_premise_servers   9.5
5               other   3.6
6                 ibm   1.2

A AWS é a opção de Cloud mais utilizada, entretanto a GCP do Google, Cloud própria e Azure(Microsoft) estão em seguida.

##### <font color= MediumSpringGreen> **Quais as Ferramentas de Business Intelligence você utiliza no trabalho?**
 </font>

In [260]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,
                                         [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],'software_BI')

software_BI     %
0              microsoft_powerbi  26.2
1                        tableau  16.3
2             google_data_studio  13.6
3                       metabase  10.9
4             only_excel_gsheets   6.8
5                          other   5.4
6           qlik_view_qlik_sense   5.0
7             no_bi_tool_at_work   4.5
8                         redash   2.7
9                       superset   1.8
10                 microstrategy   1.8
11          ibm_analytics_cognos   1.8
12          sap_business_objects   1.8
13                        looker   0.9
14  oracle_business_intelligence   0.5
15                         birst   0.0

A ferramenta de BI mais utilizada é o PowerBI, seguida pelo Tableau e o Data Studio

##### <font color= MediumSpringGreen> **Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?**
 </font>

In [261]:
f.percentual_colunas_multiplas_respostas(df_state_of_data_2019_filtrado,
                                         [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91],
                                         'software_ETL')

software_ETL     %
0                sql_&_stored_procedures  26.7
1                                pentaho  18.6
2                         apache_airflow  12.8
3   siss_sql_server_integration_services  11.0
4                                  other   9.9
5                               aws_glue   8.7
6                                alteryx   3.5
7                 oracle_data_integrator   2.9
8                                 talend   2.3
9                             sap_bw_etl   1.7
10                        ibm_data_stage   1.2
11                                 luigi   0.6

Analistas de dados utilizam em sua maior parte, utilizam StoreProcedures (SQL), Pentaho e o Apache Airflow como forma de ETL em seu dia-a-dia.

##### <font color= MediumSpringGreen> **Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?**
 </font>

Questão não pergunta nesta pesquisa.

#### <font color= MediumSpringGreen> Rotina de trabalho </font>

Não foram realizadas perguntas relacionadas a rotina de trabalho nesta pesquisa.

# <font color= MediumSpringGreen> 2021 </font>

## <font color= MediumSpringGreen> Preparação inicial dos dados </font>

### <font color= MediumSpringGreen> Verificando duplicatas </font>

In [262]:
df_state_of_data_2021.duplicated().sum()

4

In [263]:
df_state_of_data_2021[df_state_of_data_2021.duplicated(keep=False)]

('P0', 'id')  ('P1_a ', 'Idade')  \
72    yrhjxwscdfl516bibgi0kyrhait8fbnf                30.0   
73    yrhjxwscdfl516bibgi0kyrhait8fbnf                30.0   
1288  mdeq88ctdx127eztcxmdeq81poeki9ek                34.0   
1289  mdeq88ctdx127eztcxmdeq81poeki9ek                34.0   
1812  deptbnmlg4p0iuonwodept7eeluh5ov4                26.0   
1813  deptbnmlg4p0iuonwodept7eeluh5ov4                26.0   
2165  7lkav4o0fukny1644lc7lkav4o0c5wsb                26.0   
2166  7lkav4o0fukny1644lc7lkav4o0c5wsb                26.0   

     ('P1_a_a ', 'Faixa idade') ('P1_b ', 'Genero')  \
72                        30-34           Masculino   
73                        30-34           Masculino   
1288                      30-34            Feminino   
1289                      30-34            Feminino   
1812                      25-29           Masculino   
1813                      25-29           Masculino   
2165                      25-29           Masculino   
2166                      25-29           Masculino   

     ('P1_e ', 'Estado onde mora') ('P1_e_a ', 'uf onde mora')  \
72                    Alagoas (AL)                          AL   
73                    Alagoas (AL)                          AL   
1288                  Paraíba (PB)                          PB   
1289                  Paraíba (PB)                          PB   
1812                    Goiás (GO)                          GO   
1813                    Goiás (GO)                          GO   
2165             Minas Gerais (MG)                          MG   
2166             Minas Gerais (MG)                          MG   

     ('P1_e_b ', 'Regiao onde mora') ('P1_g_b ', 'Regiao de origem')  \
72                          Nordeste                             NaN   
73                          Nordeste                             NaN   
1288                        Nordeste                             NaN   
1289                        Nordeste                             NaN   
1812                    Centro-oeste                           Norte   
1813                    Centro-oeste                           Norte   
2165                         Sudeste                             NaN   
2166                         Sudeste                             NaN   

      ('P1_g_c ', 'Mudou de Estado?') ('P1_h ', 'Nivel de Ensino')  \
72                                  0                     Mestrado   
73                                  0                     Mestrado   
1288                                0             Doutorado ou Phd   
1289                                0             Doutorado ou Phd   
1812                                1                     Mestrado   
1813                                1                     Mestrado   
2165                                0        Graduação/Bacharelado   
2166                                0        Graduação/Bacharelado   

                          ('P1_i ', 'Área de Formação')  \
72    Computação / Engenharia de Software / Sistemas...   
73    Computação / Engenharia de Software / Sistemas...   
1288  Computação / Engenharia de Software / Sistemas...   
1289  Computação / Engenharia de Software / Sistemas...   
1812  Computação / Engenharia de Software / Sistemas...   
1813  Computação / Engenharia de Software / Sistemas...   
2165  Computação / Engenharia de Software / Sistemas...   
2166  Computação / Engenharia de Software / Sistemas...   

      ('P2_a ', 'Qual sua situação atual de trabalho?')  ('P2_b ', 'Setor')  \
72                                      Empregado (CLT)  Finanças ou Bancos   
73                                      Empregado (CLT)  Finanças ou Bancos   
1288                                    Empregado (CLT)  Finanças ou Bancos   
1289                                    Empregado (CLT)  Finanças ou Bancos   
1812  Vivo no Brasil e trabalho remoto para empresa ...               Outro   
1813  Vivo no Brasil e trabalho remoto para empresa ...               Outro   
2165       

In [264]:
df_state_of_data_2021.drop_duplicates(inplace=True)

Mesmo que não afetasse diretamente a análise sobre a carreira de analista de dados, decidi excluir a linha duplicada.

### <font color= MediumSpringGreen> Selecionando dados </font>

A pesquisa do State of Data abordou diversas perspectivas, por este motivo serão filtrados apenas as informações necessárias para a análise sobre a carreira de analista de dados.

In [265]:
# Seleção de colunas necessárias
df_state_of_data_2021_filtrado = df_state_of_data_2021.loc[:,[
    "('P2_a ', 'Qual sua situação atual de trabalho?')",
    "('P2_b ', 'Setor')",
    "('P2_f ', 'Cargo Atual')",
    "('P2_g ', 'Nivel')",
    "('P2_h ', 'Faixa salarial')",
    "('P2_q ', 'Atualmente qual a sua forma de trabalho?')",
    "('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')",
    "('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')",
    "('P4_a_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')",
    "('P4_a ', 'Atuacao')",
    "('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')",
    "('P4_b_a ', 'Dados relacionais (estruturados em bancos SQL)')",
    "('P4_b_b ', 'Dados armazenados em bancos NoSQL')",
    "('P4_b_c ', 'Imagens')",
    "('P4_b_d ', 'Textos/Documentos')",
    "('P4_b_e ', 'Vídeos')",
    "('P4_b_f ', 'Áudios')",
    "('P4_b_g ', 'Planilhas')",
    "('P4_b_h ', 'Dados georeferenciados')",
    "('P4_c ', 'Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?')",
    "('P4_c_a ', 'Dados relacionais (estruturados em bancos SQL)')",
    "('P4_c_b ', 'Dados armazenados em bancos NoSQL')",
    "('P4_c_c ', 'Imagens')",
    "('P4_c_d ', 'Textos/Documentos')",
    "('P4_c_e ', 'Vídeos')",
    "('P4_c_f ', 'Áudios')",
    "('P4_c_g ', 'Planilhas')",
    "('P4_c_h ', 'Dados georeferenciados')",
    "('P4_d ', 'Quais das linguagens listadas abaixo você utiliza no trabalho?')",
    "('P4_d_a ', 'SQL')",
    "('P4_d_b ', 'R ')",
    "('P4_d_c ', 'Python')",
    "('P4_d_d ', 'C/C++/C#')",
    "('P4_d_e ', '.NET')",
    "('P4_d_f ', 'Java')",
    "('P4_d_g ', 'Julia')",
    "('P4_d_h ', 'SAS/Stata')",
    "('P4_d_i ', 'Visual Basic/VBA')",
    "('P4_d_j ', 'Scala')",
    "('P4_d_k ', 'Matlab')",
    "('P4_d_l ', 'PHP')",
    "('P4_d_m ', 'Javascript')",
    "('P4_d_n ', 'Não utilizo nenhuma linguagem')",
    "('P4_e ', 'Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?')",
    "('P4_e_a ', 'SQL')",
    "('P4_e_b ', 'R ')",
    "('P4_e_c ', 'Python')",
    "('P4_e_d ', 'C/C++/C#')",
    "('P4_e_e ', '.NET')",
    "('P4_e_f ', 'Java')",
    "('P4_e_g ', 'Julia')",
    "('P4_e_h ', 'SAS/Stata')",
    "('P4_e_i ', 'Visual Basic/VBA')",
    "('P4_e_j ', 'Scala')",
    "('P4_e_k ', 'Matlab')",
    "('P4_e_l ', 'PHP')",
    "('P4_e_m ', 'Javascript')",
    "('P4_e_n ', 'Não utilizo nenhuma linguagem')",
    "('P4_f ', 'Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?')",
    "('P4_f_a ', 'MySQL')",
    "('P4_f_b ', 'Oracle')",
    "('P4_f_c ', 'SQL SERVER')",
    "('P4_f_d ', 'SAP')",
    "('P4_f_e ', 'Amazon Aurora ou RDS')",
    "('P4_f_f ', 'Amazon DynamoDB')",
    "('P4_f_g ', 'CoachDB')",
    "('P4_f_h ', 'Cassandra')",
    "('P4_f_i ', 'MongoDB')",
    "('P4_f_j ', 'MariaDB')",
    "('P4_f_k ', 'Datomic')",
    "('P4_f_l ', 'S3')",
    "('P4_f_m ', 'PostgreSQL')",
    "('P4_f_n ', 'ElasticSearch')",
    "('P4_f_o ', 'DB2')",
    "('P4_f_p ', 'Microsoft Access')",
    "('P4_f_q ', 'SQLite')",
    "('P4_f_r ', 'Sybase')",
    "('P4_f_s ', 'Firebase')",
    "('P4_f_t ', 'Vertica')",
    "('P4_f_u ', 'Redis')",
    "('P4_f_v ', 'Neo4J')",
    "('P4_f_x ', 'Google BigQuery')",
    "('P4_f_y ', 'Google Firestore')",
    "('P4_f_z ', 'Amazon Redshift')",
    "('P4_f_z1 ', 'Amazon Athena')",
    "('P4_f_z2 ', 'Snowflake')",
    "('P4_f_z3 ', 'Databricks')",
    "('P4_f_z4 ', 'HBase')",
    "('P4_f_z5 ', 'Presto')",
    "('P4_f_z6 ', 'Splunk')",
    "('P4_f_z7 ', 'SAP HANA')",
    "('P4_f_z8 ', 'Hive')",
    "('P4_f_z9 ', 'Firebird')",
    "('P4_g ', 'Quais das opções de Cloud listadas abaixo você utiliza no trabalho?')",
    "('P4_g_a ', 'Amazon Web Services (AWS)')",
    "('P4_g_b ', 'Google Cloud (GCP)')",
    "('P4_g_c ', 'Azure (Microsoft)')",
    "('P4_g_d ', 'Oracle Cloud')",
    "('P4_g_e ', 'IBM')",
    "('P4_g_f ', 'Servidores On Premise/Não utilizamos Cloud')",
    "('P4_g_g ', 'Cloud Própria')",
    "('P4_h ', 'Quais as Ferramentas de Business Intelligence você utiliza no trabalho?')",
    "('P4_h_a ', 'Microsoft PowerBI')",
    "('P4_h_b ', 'Qlik View/Qlik Sense')",
    "('P4_h_c ', 'Tableau')",
    "('P4_h_d ', 'Metabase')",
    "('P4_h_e ', 'Superset')",
    "('P4_h_f ', 'Redash')",
    "('P4_h_g ', 'MicroStrategy')",
    "('P4_h_c ', 'Tableau')",
    "('P4_h_d ', 'Metabase')",
    "('P4_h_e ', 'Superset')",
    "('P4_h_f ', 'Redash')",
    "('P4_h_g ', 'MicroStrategy')",
    "('P4_h_h ', 'IBM Analytics/Cognos')",
    "('P4_h_i ', 'SAP Business Objects')",
    "('P4_h_j ', 'Oracle Business Intelligence')",
    "('P4_h_k ', 'Amazon QuickSight')",
    "('P4_h_l ', 'Salesforce/Einstein Analytics')",
    "('P4_h_m ', 'Mode')",
    "('P4_h_n ', 'Alteryx')",
    "('P4_h_o ', 'Birst')",
    "('P4_h_p ', 'Looker')",
    "('P4_h_q ', 'Google Data Studio')",
    "('P4_h_r ', 'SAS Visual Analytics')",
    "('P4_h_s ', 'Grafana')",
    "('P4_h_t ', 'TIBCO Spotfire')",
    "('P4_h_u ', 'Pentaho')",
    "('P4_h_v ', 'Fazemos todas as análises utilizando apenas Excel ou planilhas do google')",
    "('P4_h_x ', 'Não utilizo nenhuma ferramenta de BI no trabalho')",
    "('P7_a ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?')",
    "('P7_a_a ', 'Processo e analiso dados utilizando linguagens de programação como Python, R etc.')",
    "('P7_a_b ', 'Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')",
    "('P7_a_c ', 'Utilizo API's para extrair dados e complementar minhas análises.')",
    "('P7_a_d ', 'Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')",
    "('P7_a_e ', 'Desenvolvo/cuido da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')",
    "('P7_a_f ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')",
    "('P7_a_g ', 'Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.')",
    "('P7_a_h ', 'Utilizo ferramentas avançadas de estatística como SAS')",
    "('P7_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?')",
    "('P7_b_a ', 'Scripts Python')",
    "('P7_b_b ', 'SQL & Stored Procedures')",
    "('P7_b_c ', 'Apache Airflow')",
    "('P7_b_d ', 'Luigi')",
    "('P7_b_e ', 'AWS Glue')",
    "('P7_b_f ', 'Talend')",
    "('P7_b_g ', 'Stitch')",
    "('P7_b_h ', 'Fivetran')",
    "('P7_b_i ', 'Google Dataflow')",
    "('P7_b_j ', 'Oracle Data Integrator')",
    "('P7_b_k ', 'IBM DataStage')",
    "('P7_b_l ', 'SAP BW ETL')",
    "('P7_b_m ', 'SQL Server Integration Services (SSIS)')",
    "('P7_b_n ', 'SAS Data Integration')",
    "('P7_b_o ', 'Qlik Sense')",
    "('P7_b_p ', 'Knime')",
    "('P7_b_l ', 'SAP BW ETL')",
    "('P7_b_m ', 'SQL Server Integration Services (SSIS)')",
    "('P7_b_n ', 'SAS Data Integration')",
    "('P7_b_o ', 'Qlik Sense')",
    "('P7_b_p ', 'Knime')",
    "('P7_b_q ', 'Não utilizo ferramentas de ETL')",
    "('P7_c ', 'Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?')",
    "('P7_c_a ', 'Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.')",
    '(\'P7_c_b \', \'""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.\')',
    "('P7_c_c ', 'Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.')",
    "('P7_c_d ', 'Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.')",
    "('P7_c_e ', 'Minha empresa não utiliza essas ferramentas.')",
    "('P7_c_f ', 'Não sei informar.')",
    "('P7_d ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo de trabalho?')",
    "('P7_d_a ', 'Processando e analisando dados utilizando linguagens de programação como Python, R etc.')",
    "('P7_d_b ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')",
    "('P7_d_c ', 'Utilizando API's para extrair dados e complementar minhas análises.')",
    "('P7_d_d ', 'Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')",
    "('P7_d_e ', 'Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')",
    "('P7_d_f ', 'Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')",
    "('P7_d_g ', 'Desenvolvendo/cuidando da manutenção de planilhas do Excel ou Google Sheets para atender as áreas de negócio.')",
    "('P7_d_h ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')"
    ]]


Foram selecionados apenas os participantes da pesquisa que se declararam atuando como Analista de Dados. 

Foram excluídos os participantes que atuam como estagiários, pois o período de estágio (mesmo que remunerado) ainda é uma fase de maior aprendizado e está atrelada a formação da pessoa. 

Para fins de entendimento, também foram filtrados os analistas de dados que atuam no Brasil separando dos que atuam no exterior ou para o exterior (como trabalho remoto).

In [266]:
#Filtro de cargo "Analista de dados"
df_analista_dados = df_state_of_data_2021_filtrado[df_state_of_data_2021_filtrado["('P2_f ', 'Cargo Atual')"] == 'Analista de Dados/Data Analyst']

# Exluindo estagiário
situacao_trabalho = df_analista_dados["('P2_a ', 'Qual sua situação atual de trabalho?')"]
df_analista_dados = df_analista_dados.loc[(situacao_trabalho != 'Estagiário')]

#Filtrando analistas de dados que trabalham no Brasil
df_analista_dados_brasil = df_analista_dados.loc[(situacao_trabalho == 'Empregado (CLT)') | (situacao_trabalho == 'Servidor Público') | (situacao_trabalho == 'Empreendedor ou Empregado (CNPJ)') | (situacao_trabalho == 'Freelancer') ]

#Filtrando analistas de dados que trabalham no exterior ou para o exterior
df_analista_dados_exterior = df_analista_dados.loc[(situacao_trabalho == 'Vivo fora do Brasil e trabalho para empresa de fora do Brasil') | (situacao_trabalho == 'Vivo no Brasil e trabalho remoto para empresa de fora do Brasil (PJ)')]

In [267]:
#Alterando nomenclatura da faixa salarial
faixa_salarial = {
    'de R$ 6.001/mês a R$ 8.000/mês' : 'de 6 à 8 mil reais/mês',
    'de R$ 4.001/mês a R$ 6.000/mês' : 'de 4 à 6 mil reais/mês',
    'de R$ 8.001/mês a R$ 12.000/mês': 'de 8 à 12 mil reais/mês',
    'de R$ 3.001/mês a R$ 4.000/mês': 'de 3 à 4 mil reais/mês',
    'de R$ 2.001/mês a R$ 3000/mês': 'de 2 à 3 mil reais/mês',
    'de R$ 12.001/mês a R$ 16.000/mês': 'de 12 à 16 mil reais/mês',
    'de R$ 1.001/mês a R$ 2.000/mês': 'de 1 à 2 mil reais/mês',
    'de R$ 20.001/mês a R$ 25.000/mês':'de 20 à 25 mil reais/mês',
    'de R$ 25.001/mês a R$ 30.000/mês': 'de 25 à 30 mil reais/mês',
    'de R$ 30.001/mês a R$ 40.000/mês': 'de 30 à 40 mil reais/mês',
    'de R$ 16.001/mês a R$ 20.000/mês':'de 16 à 20 mil reais/mês'
}

df_analista_dados.loc[:,"('P2_h ', 'Faixa salarial')"] = df_analista_dados.loc[:,"('P2_h ', 'Faixa salarial')"].map(faixa_salarial)
  

## <font color= MediumSpringGreen> Análise dos dados </font>

### <font color= MediumSpringGreen> Total da amostra </font>

In [268]:
quantidade_amostra_total = len(df_analista_dados)
quantidade_amostra_brasil = len(df_analista_dados_brasil)
quantidade_amostra_exterior = len(df_analista_dados_exterior)

print(f'A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de {quantidade_amostra_total}.\nDesses, {quantidade_amostra_brasil} trabalham no Brasil e {quantidade_amostra_exterior} trabalham para/no exterior.')

A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de 299.
Desses, 288 trabalham no Brasil e 11 trabalham para/no exterior.


### <font color= MediumSpringGreen> Atuação profissional </font>

A atuação profissional nem sempre correponde a nomenclatura do cargo, existem profissionais que são analistas de dados, mas atuam com engenharia ou ciência de dados. 

Por este motivo verificarei o percentual da atuação.

In [269]:
freq_atuacao = f.tabela_frequencia(df_analista_dados,"('P4_a ', 'Atuacao')")
freq_atuacao

Atuacao     %
0     Análise de Dados  87.3
1  Engenharia de Dados   5.4
2     Ciência de Dados   4.7
3                Outra   2.7

In [270]:
f.grafico_barras(freq_atuacao,'Atuação','Percentual de frequência de Atuação','cores_uma_barra',5)

Um fração de 87.3% da amostra atuam de fato com análise de dados.
Os demais 12.7%, atuam na prática com outras frentes, como: engenharia de dados e ciência de dados.

### <font color= MediumSpringGreen> Analistas de dados </font>

A partir deste cenário, irei verificar apenas os dados dos profissionais que responderam atuarem de fato com "Análise de Dados".

In [271]:
df_analista_dados_puro = df_analista_dados[df_analista_dados["('P4_a ', 'Atuacao')"]=='Análise de Dados']
quantidade_amostra_real = len(df_analista_dados_puro)
print(f'A quantidade da amostra total de analistas de dados (atuando apenas com análise de dados) que responderam a pesquisa foi de {quantidade_amostra_real}.')


A quantidade da amostra total de analistas de dados (atuando apenas com análise de dados) que responderam a pesquisa foi de 261.


#### <font color= MediumSpringGreen> Setor </font>

In [272]:
freq_setor = f.tabela_frequencia(df_analista_dados_puro,"('P2_b ', 'Setor')")
freq_setor

Setor     %
0               Finanças ou Bancos  18.4
1   Tecnologia/Fábrica de Software  18.0
2                           Varejo   8.0
3                         Educação   7.7
4               Internet/Ecommerce   6.1
5                    Área da Saúde   6.1
6                            Outro   5.0
7                    Setor Público   4.6
8                        Indústria   4.6
9                Setor Alimentício   3.4
10                 Telecomunicação   2.7
11                       Marketing   2.7
12                     Imobiliário   2.7
13                    Agronegócios   2.3
14      Entretenimento ou Esportes   1.5
15                         Energia   1.1
16                Construção Civil   1.1
17          Seguros ou Previdência   1.1
18                        Serviços   1.1
19                     Consultoria   0.8
20                Setor Automotivo   0.8

In [273]:
f.grafico_barras(freq_setor,'Setor','Top 10: Percentual de frequência de Setor','cores_duas_barras',10)

:Os setores que mais empregam analistas de dados é o de finanças (18.4%) e o de tecnologia (18%).

#### <font color= MediumSpringGreen> Nível </font>

In [274]:
freq_nivel = f.tabela_frequencia(df_analista_dados_puro,"('P2_g ', 'Nivel')")
freq_nivel

Nivel     %
0  Sênior  33.3
1   Pleno  33.3
2  Júnior  33.3

In [275]:
f.grafico_barras(freq_nivel,'Nível','Percentual de frequência de Nível','cores_todas_barras',3)

Os profissional da amostra estavam divididos em 3 grupos de tamanhos iguais (87 participantes) entre Sênior, Pleno e Júnior.

##### <font color= MediumSpringGreen> Filtro de cargo entre os participantes </font>

In [276]:
senior = df_analista_dados_puro[df_analista_dados_puro["('P2_g ', 'Nivel')"] == 'Sênior']
pleno = df_analista_dados_puro[df_analista_dados_puro["('P2_g ', 'Nivel')"] == 'Pleno']
junior = df_analista_dados_puro[df_analista_dados_puro["('P2_g ', 'Nivel')"] == 'Júnior']

#### <font color= MediumSpringGreen> Situação de trabalho </font>

In [277]:
freq_situacao_trabalho = f.tabela_frequencia(df_analista_dados_puro,"('P2_a ', 'Qual sua situação atual de trabalho?')")
freq_situacao_trabalho

Qual sua situação atual de trabalho?     %
0                                    Empregado (CLT)  87.7
1                                   Servidor Público   5.7
2  Vivo fora do Brasil e trabalho para empresa de...   2.3
3                   Empreendedor ou Empregado (CNPJ)   1.9
4  Vivo no Brasil e trabalho remoto para empresa ...   1.9
5                                         Freelancer   0.4

In [278]:
f.grafico_barras(freq_situacao_trabalho,'Situação de trabalho','Percentual de frequência de Nível','cores_uma_barra',6)

A maior parte dos profissionais (87.7%) atuam de forma CLT. 

#### <font color= MediumSpringGreen> Faixa salarial </font>

In [279]:
freq_faixa_salarial = f.tabela_frequencia(df_analista_dados_puro,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial

Faixa salarial     %
0     de 6 à 8 mil reais/mês  24.5
1     de 4 à 6 mil reais/mês  23.8
2    de 8 à 12 mil reais/mês  23.4
3     de 3 à 4 mil reais/mês  11.9
4     de 2 à 3 mil reais/mês   6.1
5   de 12 à 16 mil reais/mês   5.0
6     de 1 à 2 mil reais/mês   2.3
7   de 20 à 25 mil reais/mês   1.5
8   de 25 à 30 mil reais/mês   0.8
9   de 30 à 40 mil reais/mês   0.4
10  de 16 à 20 mil reais/mês   0.4

In [280]:
f.grafico_barras(freq_faixa_salarial,'Faixa salarial','Top 10: Percentual de frequência de Faixa Salarial','cores_tres_barras',10)

A faixa salarial geral majoritária do cargo está entre 4 e 12 mil reais.

##### <font color= MediumSpringGreen> Senior </font>




In [281]:
freq_faixa_salarial_senior = f.tabela_frequencia(senior,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_senior

Faixa salarial     %
0   de 8 à 12 mil reais/mês  46.0
1    de 6 à 8 mil reais/mês  29.9
2  de 12 à 16 mil reais/mês  11.5
3    de 4 à 6 mil reais/mês   5.7
4    de 3 à 4 mil reais/mês   2.3
5  de 25 à 30 mil reais/mês   1.1
6  de 20 à 25 mil reais/mês   1.1
7    de 1 à 2 mil reais/mês   1.1
8  de 16 à 20 mil reais/mês   1.1

In [282]:
f.grafico_barras(freq_faixa_salarial_senior,'Faixa salarial','Top 10: Percentual de frequência de Faixa Salarial de profissionais Sênior','cores_tres_barras',10)

Para o nível Sênior, a faixa está entre 6 e 16 mil reais.


##### <font color= MediumSpringGreen> Pleno </font>


In [283]:
freq_faixa_salarial_pleno = f.tabela_frequencia(pleno,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_pleno

Faixa salarial     %
0    de 6 à 8 mil reais/mês  34.5
1    de 4 à 6 mil reais/mês  28.7
2   de 8 à 12 mil reais/mês  18.4
3    de 3 à 4 mil reais/mês   8.0
4  de 20 à 25 mil reais/mês   3.4
5  de 12 à 16 mil reais/mês   2.3
6    de 2 à 3 mil reais/mês   2.3
7    de 1 à 2 mil reais/mês   1.1
8  de 25 à 30 mil reais/mês   1.1

In [284]:
f.grafico_barras(freq_faixa_salarial_pleno,'Faixa salarial','Top 10: Percentual de frequência de Faixa Salarial de profissionais Pleno','cores_tres_barras',10)

Para o nível Pleno, a faixa está entre 4 e 8 mil reais.

##### <font color= MediumSpringGreen> Júnior </font>


In [285]:
freq_faixa_salarial_junior = f.tabela_frequencia(junior,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_junior

Faixa salarial     %
0    de 4 à 6 mil reais/mês  36.8
1    de 3 à 4 mil reais/mês  25.3
2    de 2 à 3 mil reais/mês  16.1
3    de 6 à 8 mil reais/mês   9.2
4   de 8 à 12 mil reais/mês   5.7
5    de 1 à 2 mil reais/mês   4.6
6  de 12 à 16 mil reais/mês   1.1
7  de 30 à 40 mil reais/mês   1.1

In [286]:
f.grafico_barras(freq_faixa_salarial_junior,'Faixa salarial','Top 10: Percentual de frequência de Faixa Salarial de profissionais Júnior','cores_tres_barras',10)

Para o nível Pleno, a faixa está entre 2 e 4 mil reais.

#### <font color= MediumSpringGreen> Tempo de experiência </font>

In [287]:
freq_tempo_experiencia_TI = f.tabela_frequencia(df_analista_dados_puro,
                                              "('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')")
freq_tempo_experiencia_TI

Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?  \
0  Não tive experiência na área de TI/Engenharia ...                                                                          
1                                     Menos de 1 ano                                                                          
2                                      de 1 a 2 anos                                                                          
3                                    Mais de 10 anos                                                                          
4                                      de 2 a 3 anos                                                                          
5                                     de 6 a 10 anos                                                                          
6                                      de 4 a 5 anos                                                                          

      %  
0  51.3  
1  20.3  
2   8.8  
3   5.7  
4   5.7  
5   4.2  
6   3.8

In [288]:
#Ajuste na informação para deixá-la mais objetiva
freq_tempo_experiencia_TI.iloc[:,0] = freq_tempo_experiencia_TI.iloc[:,0].replace('Não tive experiência na área de TI/Engenharia de Software antes de começar a trabalhar na área de dados',
                                            'Não tive experiência na área')

In [289]:
f.grafico_barras(freq_tempo_experiencia_TI,'Tempo de experiência',
               'Percentual de frequência do tempo de experiência na área de <br>TI/Engenharia de software antes de começar a trabalhar na área de dados',
               'cores_duas_barras',7)

Mais da metade dos profissionais não tiveram uma experiência na área de tecnologia antes de atuar no cargo.


In [290]:
freq_tempo_experiencia_dados = f.tabela_frequencia(df_analista_dados_puro,"('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')")
freq_tempo_experiencia_dados

Quanto tempo de experiência na área de dados você tem?     %
0                                      de 2 a 3 anos      25.3
1                                     Menos de 1 ano      20.7
2                                      de 1 a 2 anos      19.2
3                                      de 4 a 5 anos      16.5
4                                     de 6 a 10 anos      12.3
5                                    Mais de 10 anos       5.7
6             Não tenho experiência na área de dados       0.4

In [291]:
f.grafico_barras(freq_tempo_experiencia_dados,'Tempo de experiência',
               'Percentual de frequência do tempo de experiência na área de dados',
               'cores_tres_barras',7)

Devido a aceleração do crescimento na área de dados dos últimos 5-10 anos, a maior parte dos profissionais tem entre 0 e 5 anos de experiência.


Por ser uma área de dados ainda muito próxima do negócio, pode ser uma porta de entrada para os profissionais que desejam "migrar" ou apenas estarem mais próximos da tecnologia.

#### <font color= MediumSpringGreen> Ferramentas </font>

##### <font color= MediumSpringGreen> **Quais das fontes de dados listadas você já analisou ou processou no trabalho?** </font>

In [292]:
freq_fontes_dados = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[11,12,13,14,15,16,17,18],'fontes_dados')
freq_fontes_dados

fontes_dados     %
0                                       Planilhas  30.9
1  Dados relacionais (estruturados em bancos SQL)  30.0
2                               Textos/Documentos  15.6
3               Dados armazenados em bancos NoSQL   9.8
4                          Dados georeferenciados   9.8
5                                         Imagens   2.5
6                                          Áudios   0.8
7                                          Vídeos   0.6

In [293]:
f.grafico_barras(freq_fontes_dados,'Fontes de dados',
               'Percentual de frequência das fontes de dados já analisadas',
               'cores_duas_barras',8)

##### <font color= MediumSpringGreen> **Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?** </font>

In [294]:
freq_fontes_dados_mais_utilizadas = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[20,21,22,23,24,25,26,27],'fontes_dados_mais_utilizadas')
freq_fontes_dados_mais_utilizadas

fontes_dados_mais_utilizadas     %
0  Dados relacionais (estruturados em bancos SQL)  49.2
1                                       Planilhas  40.0
2               Dados armazenados em bancos NoSQL   4.9
3                               Textos/Documentos   4.3
4                          Dados georeferenciados   1.6
5                                         Imagens   0.0
6                                          Vídeos   0.0
7                                          Áudios   0.0

In [295]:
f.grafico_barras(freq_fontes_dados_mais_utilizadas,'Fontes de dados',
               'Percentual de frequência das fontes de dados mais utilizadas',
               'cores_duas_barras',5)

Dentre as fontes processadas e mais utilizadas pelos profissionais estão as planilhas e os bancos de dados relacionais (SQL). Por se tratarem de profissionais que atuem com informações mais estruturadas é esperado esse resultado.

##### <font color= MediumSpringGreen> **Quais das linguagens listadas abaixo você utiliza no trabalho?**
 </font>

In [296]:
freq_fontes_linguagens_utilizadas = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[29,30,31,32,33,34,35,36,37,38,39,40,41,42],'linguagens_mais_utilizadas')
freq_fontes_linguagens_utilizadas

linguagens_mais_utilizadas     %
0                             SQL  40.7
1                          Python  33.0
2                              R    8.4
3                Visual Basic/VBA   4.5
4                       SAS/Stata   2.9
5   Não utilizo nenhuma linguagem   2.5
6                            Java   2.3
7                      Javascript   2.1
8                          Matlab   1.1
9                             PHP   0.9
10                          Scala   0.7
11                       C/C++/C#   0.5
12                           .NET   0.4
13                          Julia   0.0

In [297]:
f.grafico_barras(freq_fontes_linguagens_utilizadas,'Linguagens utilizadas',
               'Percentual de frequência das linguagens utilizadas',
               'cores_duas_barras',13)

##### <font color= MediumSpringGreen> **Entre as linguagens listadas abaixo, qual é a que você mais utiliza no trabalho?**
 </font>

In [298]:
freq_fontes_linguagens_mais_utilizadas = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[44,45,46,47,48,49,50,51,52,53,54,55,56,57],'linguagens_mais_utilizadas')
freq_fontes_linguagens_mais_utilizadas

linguagens_mais_utilizadas     %
0                             SQL  63.2
1                          Python  21.1
2   Não utilizo nenhuma linguagem   5.4
3                              R    4.6
4                Visual Basic/VBA   2.7
5                       SAS/Stata   2.3
6                           Scala   0.8
7                        C/C++/C#   0.0
8                            .NET   0.0
9                            Java   0.0
10                          Julia   0.0
11                         Matlab   0.0
12                            PHP   0.0
13                     Javascript   0.0

In [299]:
f.grafico_barras(freq_fontes_linguagens_mais_utilizadas,'Linguagens mais utilizadas',
               'Percentual de frequência das linguagens mais utilizadas',
               'cores_duas_barras',7)

Dentre as linguagens, lideram o SQL e Python, mas R, VBA ou mesmo a não utilização de linguagens de programação estão entre as próximas.

##### <font color= MediumSpringGreen> **Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?**
 </font>

In [300]:
freq_banco_dados_utilizadas = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,
                                                                                [59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92],
                                                                                'SGBD')
freq_banco_dados_utilizadas

SGBD     %
0             SQL SERVER  15.1
1                  MySQL  10.5
2        Google BigQuery   9.1
3             PostgreSQL   9.1
4                 Oracle   8.0
5             Databricks   5.2
6                     S3   5.1
7          Amazon Athena   4.6
8        Amazon Redshift   4.3
9                   Hive   3.4
10               MongoDB   3.2
11      Microsoft Access   2.8
12              Firebase   2.6
13             Snowflake   2.5
14                Presto   2.2
15              SAP HANA   1.9
16                   SAP   1.9
17                SQLite   1.5
18               MariaDB   1.5
19  Amazon Aurora ou RDS   1.1
20         ElasticSearch   1.1
21       Amazon DynamoDB   0.8
22                 HBase   0.6
23                   DB2   0.6
24                Splunk   0.5
25                 Redis   0.3
26              Firebird   0.2
27      Google Firestore   0.2
28             Cassandra   0.2
29                 Neo4J   0.0
30               Vertica   0.0
31               Datomic   0.0
32               CoachDB   0.0
33                Sybase   0.0

In [301]:
f.grafico_barras(freq_banco_dados_utilizadas,"SGBD's utilizados",
               "Top 10: Percentual de frequência dos SGBD's utilizadas",
               'cores_duas_barras',10)

O banco de dados com maior uso entre os profissionais é o SQL Server.

Esse pode ser um sinal de que profissionais que queiram entrar no mercado, conheçam a ferramenta para aumentar a probabilidade de oportunidades.

##### <font color= MediumSpringGreen> **Quais das opções de Cloud listadas abaixo você utiliza no trabalho?**
 </font>

In [302]:
freq_cloud_utilizada = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[94,95,96,97,98,99,100],'cloud')
freq_cloud_utilizada

cloud     %
0                   Amazon Web Services (AWS)  31.5
1                           Azure (Microsoft)  21.3
2                          Google Cloud (GCP)  19.8
3  Servidores On Premise/Não utilizamos Cloud  16.7
4                               Cloud Própria   5.9
5                                Oracle Cloud   4.6
6                                         IBM   0.3

In [303]:
f.grafico_barras(freq_cloud_utilizada,"Opções de Cloud",
               "Percentual de frequência das opções de Cloud utilizadas",
               'cores_uma_barra',7)

A AWS é a opção de Cloud mais utilizada, entretanto há uma grande fatia para a Azure, Google Cloud e empresas que não utilizam Cloud.

##### <font color= MediumSpringGreen> **Quais as Ferramentas de Business Intelligence você utiliza no trabalho?**
 </font>

In [304]:
freq_BI = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,
                                       [102,103,104,105,106,107,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129],'software_BI')
freq_BI

software_BI     %
0                                   Microsoft PowerBI  32.9
1                                  Google Data Studio  12.8
2                                             Tableau  10.8
3   Fazemos todas as análises utilizando apenas Ex...   7.1
4                                            Metabase   6.5
5                                              Looker   6.5
6                                Qlik View/Qlik Sense   3.2
7                                             Alteryx   3.2
8    Não utilizo nenhuma ferramenta de BI no trabalho   1.9
9                                   Amazon QuickSight   1.7
10                                             Redash   1.7
11                                      MicroStrategy   1.5
12                                            Pentaho   1.5
13                      Salesforce/Einstein Analytics   1.5
14                               SAP Business Objects   1.3
15                       Oracle Business Intelligence   1.1
16                               IBM Analytics/Cognos   1.1
17                               SAS Visual Analytics   1.1
18                                            Grafana   1.1
19                                     TIBCO Spotfire   0.6
20                                           Superset   0.4
21                                               Mode   0.2
22                                              Birst   0.0

In [305]:
f.grafico_barras(freq_BI,"Ferramentas de BI",
               "Top 10: Percentual de frequência das ferramentas de BI utilizadas",
               'cores_uma_barra',10)

O Power BI é a ferramenta que lidera entre os analistas de dados e pode ser uma boa opção de entrada para quem deseja entrar no mercado.

##### <font color= MediumSpringGreen> **Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?**
 </font>

In [306]:
freq_ETL = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,
                                                  [140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,160,161],
                                                  'sofware_ETL')
freq_ETL

sofware_ETL     %
0                           Scripts Python  34.4
1                  SQL & Stored Procedures  32.5
2           Não utilizo ferramentas de ETL  12.2
3   SQL Server Integration Services (SSIS)   5.3
4                           Apache Airflow   4.8
5                     SAS Data Integration   2.6
6                                 AWS Glue   2.4
7                               Qlik Sense   1.9
8                                   Stitch   0.8
9                               SAP BW ETL   0.8
10                                   Knime   0.8
11                  Oracle Data Integrator   0.5
12                         Google Dataflow   0.5
13                                Fivetran   0.3
14                           IBM DataStage   0.3
15                                   Luigi   0.0
16                                  Talend   0.0

In [307]:
f.grafico_barras(freq_ETL,"Ferramentas de ETL",
               "Top 10: Percentual de frequência das ferramentas de ETL utilizadas",
               'cores_duas_barras',10)

Analistas de dados utilizam em sua maior parte scripts em Python e Store Procedures (SQL) como forma de ETL em seu dia-a-dia.

##### <font color= MediumSpringGreen> **Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?**
 </font>

In [308]:
freq_software_otimizacao = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[163,164,165,166,167,168],
                                                                  'software')
#Ajuste para deixar a informação mais objetiva
freq_software_otimizacao['software'] = freq_software_otimizacao['software'].replace('Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
                                             'Salesforce Einstein Anaytics ou Zendesk dashboards.')
freq_software_otimizacao

software     %
0       Minha empresa não utiliza essas ferramentas.  35.5
1                                  Não sei informar.  29.7
2  Salesforce Einstein Anaytics ou Zendesk dashbo...  14.1
3         ""Point and Click"" Analytics como Alteryx   9.7
4          Product metricts & Insights como Mixpanel   7.9
5                  Ferramentas de AutoML como H2O.ai   3.1

In [309]:
f.grafico_barras(freq_software_otimizacao,"Respostas",
               "Percentual de frequência das ferramentas de autonomia em análise de dados <br>para as áreas de negócios",
               'cores_duas_barras',6)

A maior parte das empresas ainda não utilizam ferramentas de otimização de análise de dados.

#### <font color= MediumSpringGreen> Rotina de trabalho </font>

##### <font color= MediumSpringGreen> **Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?**
 </font>

In [310]:
freq_rotina = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[131,132,133,134,135,136,137,138],
                                                     'rotina')
freq_rotina

rotina     %
0  Realizo construções de dashboards em ferrament...  28.0
1  Processo e analiso dados utilizando linguagens...  21.2
2  Desenvolvo/cuido da manutenção de planilhas pa...  13.8
3  Realizo experimentos e estudos utilizando meto...  12.4
4                                        Utilizo API   8.5
5                        Atuo na modelagem dos dados   7.2
6              Desenvolvo/cuido da manutenção de ETL   7.0
7  Utilizo ferramentas avançadas de estatística c...   1.9

In [311]:
f.grafico_barras(freq_rotina,"Atividades",
               "Percentual de frequência das atividades da rotina de trabalho",
               'cores_duas_barras',6)

##### <font color= MediumSpringGreen> **Em qual das opções abaixo você gasta a maior parte do seu tempo de trabalho?**
 </font>

In [312]:
freq_tempo = f.percentual_colunas_multiplas_respostas(df_analista_dados_puro,[170,171,172,173,174,175,176,177],
                                                    'atividade')
freq_tempo

atividade     %
0  Realizando construções de dashboards em ferram...  46.8
1  Processando e analisando dados utilizando ling...  28.7
2  Desenvolvendo/cuidando da manutenção de planil...  10.5
3        Desenvolvendo/cuidando da manutenção de ETL   4.1
4                     Atuando na modelagem dos dados   4.1
5  Realizando experimentos e estudos utilizando m...   3.2
6  Utilizando ferramentas avançadas de estatístic...   1.6
7                                     Utilizando API   1.0

In [313]:
f.grafico_barras(freq_tempo,"Atividade",
               "Percentual de frequência das atividades onde se gasta a maior parte do tempo",
               'cores_duas_barras',8)

A rotina de um analista de dados é em sua maior parte, desenvolver Dashboards, processar e analisar dados, desenvolver e dar manutenção a planilhas das áreas de negócios e realizar estudos estatísticos para validar experimentos e hipóteses das análises.

# <font color= MediumSpringGreen> 2022 </font>

## <font color= MediumSpringGreen> Preparação inicial dos dados </font>

### <font color= MediumSpringGreen> Verificando duplicatas </font>

In [314]:
df_state_of_data_2022.duplicated().sum()

1

In [315]:
df_state_of_data_2022[df_state_of_data_2022.duplicated(keep=False)]

('P0', 'id')  ('P1_a ', 'Idade')  \
375  x4w2zctsfwfqh3q8aphgx4w2zflx9d1u                49.0   
376  x4w2zctsfwfqh3q8aphgx4w2zflx9d1u                49.0   

    ('P1_a_1 ', 'Faixa idade') ('P1_b ', 'Genero')  \
375                      45-49            Feminino   
376                      45-49            Feminino   

    ('P1_c ', 'Cor/raca/etnia') ('P1_d ', 'PCD')  \
375                      Branca              Não   
376                      Branca              Não   

     ('P1_e ', 'experiencia_profissional_prejudicada')  \
375  Sim, acredito que a minha a experiência profis...   
376  Sim, acredito que a minha a experiência profis...   

                    ('P1_f ', 'aspectos_prejudicados')  \
375  Quantidade de oportunidades de emprego/vagas r...   
376  Quantidade de oportunidades de emprego/vagas r...   

     ('P1_g ', 'vive_no_brasil') ('P1_i ', 'Estado onde mora')  \
375                         True                   Paraná (PR)   
376                         True                   Paraná (PR)   

    ('P1_i_1 ', 'uf onde mora') ('P1_i_2 ', 'Regiao onde mora')  \
375                          PR                             Sul   
376                          PR                             Sul   

    ('P1_j ', 'Mudou de Estado?') ('P1_k ', 'Regiao de origem')  \
375                          True                           NaN   
376                          True                           NaN   

    ('P1_l ', 'Nivel de Ensino')  \
375                Pós-graduação   
376                Pós-graduação   

                         ('P1_m ', 'Área de Formação')  \
375  Computação / Engenharia de Software / Sistemas...   
376  Computação / Engenharia de Software / Sistemas...   

    ('P2_a ', 'Qual sua situação atual de trabalho?') ('P2_b ', 'Setor')  \
375                                   Empregado (CLT)      Área da Saúde   
376                                   Empregado (CLT)      Área da Saúde   

    ('P2_c ', 'Numero de Funcionarios') ('P2_d ', 'Gestor?')  \
375                      de 501 a 1.000                 True   
376                      de 501 a 1.000                 True   

    ('P2_e ', 'Cargo como Gestor') ('P2_f ', 'Cargo Atual')  \
375                   Gerente/Head                      NaN   
376                   Gerente/Head                      NaN   

    ('P2_g ', 'Nivel')       ('P2_h ', 'Faixa salarial')  \
375                NaN  de R$ 20.001/mês a R$ 25.000/mês   
376                NaN  de R$ 20.001/mês a R$ 25.000/mês   

    ('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')  \
375                                    Mais de 10 anos                    
376                                    Mais de 10 anos                    

    ('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')  \
375                                    Mais de 10 anos                                                                                       
376                                    Mais de 10 anos                                                                                       

    ('P2_k ', 'Você está satisfeito na sua empresa atual?')  \
375                                               True        
376                                               True        

    ('P2_l ', 'Qual o principal motivo da sua insatisfação com a empresa atual?')  \
375                                                NaN                              
376                                                NaN                              

     ('P2_l_1 ', 'Falta de oportunidade de crescimento no emprego atual')  \
375                                                NaN                      
376                                                NaN                      

     ('P2_l_2 ', 'Salário atual não corresponde ao mercado')  \
375                                                NaN         
376                             

In [316]:
df_state_of_data_2022.drop_duplicates(inplace=True)

In [317]:
df_state_of_data_2022.shape

(4270, 353)

Mesmo que não afetasse diretamente a análise sobre a carreira de analista de dados, decidi excluir a linha duplicada.

In [318]:
respostas_nulas_2022 = pd.DataFrame(df_state_of_data_2022.isna().sum(),columns=['quantidade_respostas_nulas'])\
                        .sort_values(by='quantidade_respostas_nulas',ascending=False)
respostas_nulas_2022

quantidade_respostas_nulas
('P4_i_10 ', 'Oracle Business Intelligence')                              4068
('P4_i_13 ', 'Mode')                                                      4068
('P4_i_22 ', 'Fazemos todas as análises utiliza...                        4068
('P4_i_21 ', 'Pentaho')                                                   4068
('P4_i_20 ', 'TIBCO Spotfire')                                            4068
...                                                                        ...
('P2_a ', 'Qual sua situação atual de trabalho?')                            0
('P4_a_1 ', 'Atuacao')                                                       0
('P1_g ', 'vive_no_brasil')                                                  0
('P1_l ', 'Nivel de Ensino')                                                 0
('P0', 'id')                                                                 0

[353 rows x 1 columns]

### <font color= MediumSpringGreen> Selecionando dados </font>

In [319]:
# Seleção de colunas necessárias
df_state_of_data_2022_filtrado = df_state_of_data_2022.loc[:,[
    "('P2_a ', 'Qual sua situação atual de trabalho?')",
    "('P2_b ', 'Setor')",
    "('P2_f ', 'Cargo Atual')",
    "('P2_g ', 'Nivel')",
    "('P2_h ', 'Faixa salarial')",
    "('P2_p ', 'Atualmente qual a sua forma de trabalho?')",
    "('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')",
    "('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')",
    "('P4_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')",
    "('P4_a_1 ', 'Atuacao')",
    "('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')",
    "('P4_b_1 ', 'Dados relacionais (estruturados em bancos SQL)')",
    "('P4_b_2 ', 'Dados armazenados em bancos NoSQL')",
    "('P4_b_3 ', 'Imagens')",
    "('P4_b_4 ', 'Textos/Documentos')",
    "('P4_b_5 ', 'Vídeos')",
    "('P4_b_6 ', 'Áudios')",
    "('P4_b_7 ', 'Planilhas')",
    "('P4_b_8 ', 'Dados georeferenciados')",
    "('P4_c ', 'Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?')",
    "('P4_c_1 ', 'Dados relacionais (estruturados em bancos SQL)')",
    "('P4_c_2 ', 'Dados armazenados em bancos NoSQL')",
    "('P4_c_3 ', 'Imagens')",
    "('P4_c_4 ', 'Textos/Documentos')",
    "('P4_c_5 ', 'Vídeos')",
    "('P4_c_6 ', 'Áudios')",
    "('P4_c_7 ', 'Planilhas')",
    "('P4_c_8 ', 'Dados georeferenciados')",
    "('P4_d ', 'Quais das linguagens listadas abaixo você utiliza no trabalho?')",
    "('P4_d_1 ', 'SQL')",
    "('P4_d_2 ', 'R ')",
    "('P4_d_3 ', 'Python')",
    "('P4_d_4 ', 'C/C++/C#')",
    "('P4_d_5 ', '.NET')",
    "('P4_d_6 ', 'Java')",
    "('P4_d_7 ', 'Julia')",
    "('P4_d_8 ', 'SAS/Stata')",
    "('P4_d_9 ', 'Visual Basic/VBA')",
    "('P4_d_10 ', 'Scala')",
    "('P4_d_11 ', 'Matlab')",
    "('P4_d_12 ', 'PHP')",
    "('P4_d_13 ', 'Javascript')",
    "('P4_d_14 ', 'Não utilizo nenhuma linguagem')",
    "('P4_g ', 'Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?')",
    "('P4_g_1 ', 'MySQL')",
    "('P4_g_2 ', 'Oracle')",
    "('P4_g_3 ', 'SQL SERVER')",
    "('P4_f_4 ', 'Amazon Aurora ou RDS')",
    "('P4_f_5 ', 'DynamoDB')",
    "('P4_f_6 ', 'CoachDB')",
    "('P4_f_7 ', 'Cassandra')",
    "('P4_f_8 ', 'MongoDB')",
    "('P4_f_9 ', 'MariaDB')",
    "('P4_f_10 ', 'Datomic')",
    "('P4_f_11 ', 'S3')",
    "('P4_f_12 ', 'PostgreSQL')",
    "('P4_f_13 ', 'ElasticSearch')",
    "('P4_f_14 ', 'DB2')",
    "('P4_f_15 ', 'Microsoft Access')",
    "('P4_f_16 ', 'SQLite')",
    "('P4_f_17 ', 'Sybase')",
    "('P4_f_18 ', 'Firebase')",
    "('P4_f_19 ', 'Vertica')",
    "('P4_f_20 ', 'Redis')",
    "('P4_f_21 ', 'Neo4J')",
    "('P4_f_22 ', 'Google BigQuery')",
    "('P4_f_23 ', 'Google Firestore')",
    "('P4_f_24 ', 'Amazon Redshift')",
    "('P4_f_25 ', 'Amazon Athena')",
    "('P4_f_26 ', 'Snowflake')",
    "('P4_f_27 ', 'Databricks')",
    "('P4_f_28 ', 'HBase')",
    "('P4_f_29 ', 'Presto')",
    "('P4_f_30 ', 'Splunk')",
    "('P4_f_31 ', 'SAP HANA')",
    "('P4_f_32 ', 'Hive')",
    "('P4_f_33 ', 'Firebird')",
    "('P4_g ', 'Quais das opções de Cloud listadas abaixo você utiliza no trabalho?')",
    "('P4_h_2 ', 'Amazon Web Services (AWS)')",
    "('P4_h_3 ', 'Google Cloud (GCP)')",
    "('P4_h_1 ', 'Azure (Microsoft)')",
    "('P4_i ', 'Microsoft PowerBI')",
    "('P4_i_1 ', 'Microsoft PowerBI')",
    "('P4_i_2 ', 'Qlik View/Qlik Sense')",
    "('P4_i_3 ', 'Tableau')",
    "('P4_i_4 ', 'Metabase')",
    "('P4_i_5 ', 'Superset')",
    "('P4_i_6 ', 'Redash')",
    "('P4_i_7 ', 'MicroStrategy')",
    "('P4_i_8 ', 'IBM Analytics/Cognos')",
    "('P4_i_9 ', 'SAP Business Objects')",
    "('P4_i_10 ', 'Oracle Business Intelligence')",
    "('P4_i_11 ', 'Amazon QuickSight')",
    "('P4_i_12 ', 'Salesforce/Einstein Analytics')",
    "('P4_i_13 ', 'Mode')",
    "('P4_i_14 ', 'Alteryx')",
    "('P4_i_15 ', 'Birst')",
    "('P4_i_16 ', 'Looker')",
    "('P4_i_17 ', 'Google Data Studio')",
    "('P4_i_18 ', 'SAS Visual Analytics')",
    "('P4_i_19 ', 'Grafana')",
    "('P4_i_20 ', 'TIBCO Spotfire')",
    "('P4_i_21 ', 'Pentaho')",
    "('P4_i_22 ', 'Fazemos todas as análises utilizando apenas Excel ou planilhas do google')",
    "('P4_i_23 ', 'Não utilizo nenhuma ferramenta de BI no trabalho')",
    "('P7_1 ', 'Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?')",
    "('P7_a_1 ', 'Processo e analiso dados utilizando linguagens de programação como Python, R etc.')",
    "('P7_a_2 ', 'Realizo construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')",
    "('P7_a_3 ', 'Crio consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')",
    "('P7_a_4 ', 'Utilizo API's para extrair dados e complementar minhas análises.')",
    "('P7_a_5 ', 'Realizo experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')",
    "('P7_a_6 ', 'Desenvolvo/cuido da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')",
    "('P7_a_7 ', 'Atuo na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')",
    "('P7_a_8 ', 'Desenvolvo/cuido da manutenção de planilhas para atender as áreas de negócio.')",
    "('P7_a_9 ', 'Utilizo ferramentas avançadas de estatística como SAS')",
    "('P7_a_10 ', 'Nenhuma das opções listadas refletem meu dia a dia.')",
    "('P7_b ', 'Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?')",
    "('P7_b_1 ', 'Scripts Python')",
    "('P7_b_2 ', 'SQL & Stored Procedures')",
    "('P7_b_3 ', 'Apache Airflow')",
    "('P7_b_4 ', 'Luigi')",
    "('P7_b_5 ', 'AWS Glue')",
    "('P7_b_6 ', 'Talend')",
    "('P7_b_7 ', 'Pentaho')",
    "('P7_b_8 ', 'Alteryx')",
    "('P7_b_9 ', 'Stitch')",
    "('P7_b_10 ', 'Fivetran')",
    "('P7_b_11 ', 'Google Dataflow')",
    "('P7_b_12 ', 'Oracle Data Integrator')",
    "('P7_b_13 ', 'IBM DataStage')",
    "('P7_b_14 ', 'SAP BW ETL')",
    "('P7_b_15 ', 'SQL Server Integration Services (SSIS)')",
    "('P7_b_16 ', 'SAS Data Integration')",
    "('P7_b_17 ', 'Qlik Sense')",
    "('P7_b_18 ', 'Knime')",
    "('P7_b_19 ', 'Databricks')",
    "('P7_b_20 ', 'Não utilizo ferramentas de ETL')",
    "('P7_c ', 'Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?')",
    "('P7_c_1 ', 'Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.')",
    '(\'P7_c_2 \', \'""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.\')',
    "('P7_c_3 ', 'Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.')",
    "('P7_c_4 ', 'Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.')",
    "('P7_c_5 ', 'Minha empresa não utiliza essas ferramentas.')",
    "('P7_c_6 ', 'Não sei informar.')",
    "('P7_d ', 'Em qual das opções abaixo você gasta a maior parte do seu tempo de trabalho?')",
    "('P7_d_1 ', 'Processando e analisando dados utilizando linguagens de programação como Python, R etc.')",
    "('P7_d_2 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik etc.')",
    "('P7_d_3 ', 'Criando consultas através da linguagem SQL para exportar informações e compartilhar com as áreas de negócio.')",
    "('P7_d_4 ', 'Utilizando API's para extrair dados e complementar minhas análises.')",
    "('P7_d_5 ', 'Realizando experimentos e estudos utilizando metodologias estatísticas como teste de hipótese, modelos de regressão etc.')",
    "('P7_d_6 ', 'Desenvolvendo/cuidando da manutenção de ETL's utilizando tecnologias como Talend, Pentaho, Airflow, Dataflow etc.')",
    "('P7_d_7 ', 'Atuando na modelagem dos dados, com o objetivo de criar conjuntos de dados, Data Warehouses, Data Marts etc.')",
    "('P7_d_8 ', 'Desenvolvendo/cuidando da manutenção de planilhas do Excel ou Google Sheets para atender as áreas de negócio.')",
    "('P7_d_9 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')",
    "('P7_d_10 ', 'Nenhuma das opções listadas refletem meu dia a dia.')"
    ]]


In [320]:
df_state_of_data_2022_filtrado.head(5)

('P2_a ', 'Qual sua situação atual de trabalho?')  ('P2_b ', 'Setor')  \
0                                  Servidor Público       Setor Público   
1                                   Empregado (CLT)         Outra Opção   
2                                   Empregado (CLT)  Finanças ou Bancos   
3                                   Empregado (CLT)    Setor Automotivo   
4                                  Servidor Público       Setor Público   

                            ('P2_f ', 'Cargo Atual') ('P2_g ', 'Nivel')  \
0                DBA/Administrador de Banco de Dados             Júnior   
1                                                NaN                NaN   
2  Desenvolvedor/ Engenheiro de Software/ Analist...              Pleno   
3                  Cientista de Dados/Data Scientist             Sênior   
4  Desenvolvedor/ Engenheiro de Software/ Analist...              Pleno   

        ('P2_h ', 'Faixa salarial')  \
0   de R$ 8.001/mês a R$ 12.000/mês   
1    de R$ 4.001/mês a R$ 6.000/mês   
2  de R$ 12.001/mês a R$ 16.000/mês   
3  de R$ 12.001/mês a R$ 16.000/mês   
4    de R$ 6.001/mês a R$ 8.000/mês   

  ('P2_p ', 'Atualmente qual a sua forma de trabalho?')  \
0                             Modelo 100% presencial      
1                             Modelo 100% presencial      
2  Modelo híbrido com dias fixos de trabalho pres...      
3  Modelo híbrido flexível (o funcionário tem lib...      
4                             Modelo 100% presencial      

  ('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')  \
0                                      de 1 a 2 anos                    
1                                      de 3 a 4 anos                    
2                                      de 3 a 4 anos                    
3                                      de 4 a 6 anos                    
4             Não tenho experiência na área de dados                    

  ('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')  \
0                                     de 7 a 10 anos                                                                                       
1                                     Menos de 1 ano                                                                                       
2                                    Mais de 10 anos                                                                                       
3  Não tive experiência na área de TI/Engenharia ...                                                                                       
4                                    Mais de 10 anos                                                                                       

  ('P4_a ', 'Mesmo que esse não seja seu cargo formal, você considera que sua atuação no dia a dia, reflete alguma das opções listadas abaixo?')  \
0  *Engenharia de Dados:* Modela soluções de arqu...                                                                                               
1                                                NaN                                                                                               
2  *Ciência de Dados/Machine Learning: *Desenha e...                                                                                               
3  *Ciência de Dados/Machine Learning: *Desenha e...                                                                                               
4           Não atuo em nenhuma das frentes citadas.                                                                                               

  ('P4_a_1 ', 'Atuacao')  \
0    Engenharia de Dados   
1                 Gestor   
2       Ciência de Dados   
3       Ciência de Dados   
4          Outra atuação   

  ('P4_b ', 'Quais das fontes de dados listadas você já analisou ou processou no trabalho?')  \
0  Planilhas, Textos/Documentos, Dados relacionai...                        

Foram selecionados apenas os participantes da pesquisa que se declararam atuando como Analista de Dados.

Foram excluídos os participantes que atuam como estagiários, pois o período de estágio (mesmo que remunerado) ainda é uma fase de maior aprendizado e está atrelada a formação da pessoa.

Para fins de entendimento, também foram filtrados os analistas de dados que atuam no Brasil separando dos que atuam no exterior ou para o exterior (como trabalho remoto).

In [385]:
#Filtro de cargo "Analista de dados"
df_analista_dados_2022 = df_state_of_data_2022_filtrado[df_state_of_data_2022_filtrado["('P2_f ', 'Cargo Atual')"] == 'Analista de Dados/Data Analyst']

# Exluindo estagiário
situacao_trabalho = df_analista_dados_2022["('P2_a ', 'Qual sua situação atual de trabalho?')"]
df_analista_dados_2022 = df_analista_dados_2022.loc[(situacao_trabalho != 'Estagiário')]

#Filtrando analistas de dados que trabalham no Brasil
df_analista_dados_2022_brasil = df_analista_dados_2022.loc[(situacao_trabalho == 'Empregado (CLT)') | (situacao_trabalho == 'Servidor Público') | (situacao_trabalho == 'Empreendedor ou Empregado (CNPJ)') | (situacao_trabalho == 'Freelancer') ]

#Filtrando analistas de dados que trabalham no exterior ou para o exterior
df_analista_dados_2022_exterior = df_analista_dados_2022.loc[(situacao_trabalho == 'Vivo fora do Brasil e trabalho para empresa de fora do Brasil') | (situacao_trabalho == 'Vivo no Brasil e trabalho remoto para empresa de fora do Brasil (PJ)')]

In [ ]:
df_state_of_data_2022_filtrado[df_state_of_data_2022_filtrado["('P2_f ', 'Cargo Atual')"] == 'Analista de Dados/Data Analyst']

In [322]:
#Alterando nomenclatura da faixa salarial
faixa_salarial = {
    'de R$ 6.001/mês a R$ 8.000/mês' : 'de 6 à 8 mil reais/mês',
    'de R$ 4.001/mês a R$ 6.000/mês' : 'de 4 à 6 mil reais/mês',
    'de R$ 8.001/mês a R$ 12.000/mês': 'de 8 à 12 mil reais/mês',
    'de R$ 3.001/mês a R$ 4.000/mês': 'de 3 à 4 mil reais/mês',
    'de R$ 2.001/mês a R$ 3000/mês': 'de 2 à 3 mil reais/mês',
    'de R$ 12.001/mês a R$ 16.000/mês': 'de 12 à 16 mil reais/mês',
    'de R$ 1.001/mês a R$ 2.000/mês': 'de 1 à 2 mil reais/mês',
    'de R$ 20.001/mês a R$ 25.000/mês':'de 20 à 25 mil reais/mês',
    'de R$ 25.001/mês a R$ 30.000/mês': 'de 25 à 30 mil reais/mês',
    'de R$ 30.001/mês a R$ 40.000/mês': 'de 30 à 40 mil reais/mês',
    'de R$ 16.001/mês a R$ 20.000/mês':'de 16 à 20 mil reais/mês'
}

df_analista_dados_2022.loc[:,"('P2_h ', 'Faixa salarial')"] = df_analista_dados.loc[:,"('P2_h ', 'Faixa salarial')"].map(faixa_salarial)

In [323]:
quantidade_amostra_total = len(df_analista_dados_2022)
quantidade_amostra_brasil = len(df_analista_dados_2022_brasil)
quantidade_amostra_exterior = len(df_analista_dados_2022_exterior)

print(f'A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de {quantidade_amostra_total}.\nDesses, {quantidade_amostra_brasil} trabalham no Brasil e {quantidade_amostra_exterior} trabalham para o exterior.')

A quantidade da amostra total de analistas de dados que responderam a pesquisa foi de 598.
Desses, 575 trabalham no Brasil e 8 trabalham para o exterior.


In [324]:
respostas_nulas_analista_dados_2022 = pd.DataFrame(df_analista_dados_2022.isna().sum(),columns=['quantidade_respostas_nulas'])\
                        .sort_values(by='quantidade_respostas_nulas',ascending=False)
respostas_nulas_analista_dados_2022

quantidade_respostas_nulas
('P2_h ', 'Faixa salarial')                                                598
('P4_i_16 ', 'Looker')                                                     558
('P4_i_11 ', 'Amazon QuickSight')                                          558
('P4_i_23 ', 'Não utilizo nenhuma ferramenta de...                         558
('P4_i_22 ', 'Fazemos todas as análises utiliza...                         558
...                                                                        ...
('P4_f_11 ', 'S3')                                                           0
('P4_f_12 ', 'PostgreSQL')                                                   0
('P4_f_13 ', 'ElasticSearch')                                                0
('P4_f_14 ', 'DB2')                                                          0
('P4_g ', 'Quais das opções de Cloud listadas a...                           0

[155 rows x 1 columns]

## <font color= MediumSpringGreen> Análise dos dados </font>

### <font color= MediumSpringGreen> Atuação profissional </font>

In [325]:
freq_atuacao_2022 = f.tabela_frequencia(df_analista_dados_2022,"('P4_a_1 ', 'Atuacao')")
freq_atuacao_2022

Atuacao     %
0     Análise de Dados  84.3
1     Ciência de Dados   6.9
2  Engenharia de Dados   6.4
3        Outra atuação   2.5

In [326]:
f.grafico_barras(freq_atuacao_2022,'Atuação','Atuação das pessoas Analistas de dados em 2022','cores_uma_barra',4)


### <font color= MediumSpringGreen> Analistas de dados </font>

A partir deste cenário, irei verificar apenas os dados dos profissionais que responderam atuarem de fato com "Análise de Dados".

In [390]:
df_analista_dados_2022_puro = df_analista_dados_2022[df_analista_dados_2022["('P4_a_1 ', 'Atuacao')"]=='Análise de Dados']
quantidade_amostra_real = len(df_analista_dados_2022_puro)
print(f'A quantidade da amostra total de analistas de dados (atuando apenas com análise de dados),\nque responderam a pesquisa, foi de {quantidade_amostra_real}.')


A quantidade da amostra total de analistas de dados (atuando apenas com análise de dados),
que responderam a pesquisa, foi de 504.


#### <font color= MediumSpringGreen> Setor </font>

In [328]:
freq_setor_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,"('P2_b ', 'Setor')")
freq_setor_2022

Setor     %
0        Tecnologia/Fábrica de Software  18.5
1                    Finanças ou Bancos  17.5
2                                Varejo   7.5
3                    Internet/Ecommerce   7.5
4                           Outra Opção   6.3
5                         Área da Saúde   6.2
6                             Indústria   5.0
7                   Área de Consultoria   4.4
8   Setor Imobiliário/ Construção Civil   3.8
9                             Marketing   3.6
10                         Agronegócios   3.2
11                      Telecomunicação   3.0
12                             Educação   2.8
13               Seguros ou Previdência   2.4
14                    Setor Alimentício   2.4
15                        Setor Público   2.2
16                     Setor Automotivo   1.8
17                     Setor de Energia   1.0
18                   Setor Farmaceutico   0.6
19           Entretenimento ou Esportes   0.6

Os setores que mais empregam analistas de dados é o de tecnologia/Fábrica de Software (18.5%) e o de Finanças ou Bancos (17.5%).

In [329]:
f.grafico_barras(freq_setor_2022,'Setor','Top 10: Setores de atuação das pessoas Analistas de dados em 2022','cores_duas_barras',10)


#### <font color= MediumSpringGreen> Nível </font>

In [330]:
freq_nivel_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,"('P2_g ', 'Nivel')")
freq_nivel_2022

Nivel     %
0   Pleno  39.9
1  Júnior  31.2
2  Sênior  29.0

In [331]:
f.grafico_barras(freq_nivel_2022,'Nível','Nível das pessoas Analistas de dados em 2022','cores_uma_barra',3)

#### <font color= MediumSpringGreen> Situação de trabalho </font>

In [333]:
freq_situacao_trabalho_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,"('P2_a ', 'Qual sua situação atual de trabalho?')")
freq_situacao_trabalho_2022

Qual sua situação atual de trabalho?     %
0                                    Empregado (CLT)  86.7
1                   Empreendedor ou Empregado (CNPJ)   6.5
2  Vivo no Brasil e trabalho remoto para empresa ...   2.8
3                                   Servidor Público   1.8
4  Vivo fora do Brasil e trabalho para empresa de...   1.2
5                                         Freelancer   1.0

In [334]:
f.grafico_barras(freq_situacao_trabalho_2022,'Situação de trabalho',
                 'Situação atual de trabalho das pessoas Analistas de dados em 2022','cores_uma_barra',6)


##### <font color= MediumSpringGreen> Filtro de cargo entre os participantes </font>

In [ ]:
senior_2022 = df_analista_dados_2022_puro[df_analista_dados_2022_puro["('P2_g ', 'Nivel')"] == 'Sênior']
pleno_2022 = df_analista_dados_2022_puro[df_analista_dados_2022_puro["('P2_g ', 'Nivel')"] == 'Pleno']
junior_2022 = df_analista_dados_2022_puro[df_analista_dados_2022_puro["('P2_g ', 'Nivel')"] == 'Júnior']

#### <font color= MediumSpringGreen> Faixa salarial </font>

A faixa salarial dos analistas de dados foram prejudicadas devido a quantidade de respostas nulas encontradas no conjunto de dados.

In [396]:
quantidade_total_respostas = len(df_state_of_data_2022)

respostas_nulas_faixa_salarial = df_state_of_data_2022["('P2_h ', 'Faixa salarial')"].isna().sum()
percentual_respostas_nulas_faixa_salarial = round(respostas_nulas_faixa_salarial/quantidade_total_respostas,3)*100

quantidade_total_respostas_analista_de_dados = len(df_analista_dados_2022_puro)
respostas_nulas_faixa_salarial_analista_de_dados = df_analista_dados_2022_puro["('P2_h ', 'Faixa salarial')"].isna().sum()
percentual_respostas_nulas_faixa_salarial_analista_de_dados = round(respostas_nulas_faixa_salarial_analista_de_dados/quantidade_total_respostas,3)*100

quantidade_respostas_validas_analista_dados = (quantidade_total_respostas_analista_de_dados - respostas_nulas_faixa_salarial_analista_de_dados)
percentual_quantidade_respostas_validas_analista_dados = round(quantidade_respostas_validas_analista_dados / quantidade_total_respostas_analista_de_dados,3) *100
print(
    f''' 
    Do total de {quantidade_total_respostas} (de todo o conjunto de dados da pesquisa), houveram {respostas_nulas_faixa_salarial} ({percentual_respostas_nulas_faixa_salarial:.2f}%) respostas nulas para faixa salarial.\n
    Do total de {quantidade_total_respostas_analista_de_dados} (do conjunto de dados filtrado com cargo de Analista de Dados),
    houveram {respostas_nulas_faixa_salarial_analista_de_dados} ({percentual_respostas_nulas_faixa_salarial_analista_de_dados:.2f}% do total de toda a pesquisa) respostas nulas para faixa salarial.
    ''')

 
    Do total de 4270 (de todo o conjunto de dados da pesquisa), houveram 577 (13.50%) respostas nulas para faixa salarial.

    Do total de 504 (do conjunto de dados filtrado com cargo de Analista de Dados),
    houveram 0 (0.00% do total de toda a pesquisa) respostas nulas para faixa salarial.
    


In [397]:
freq_faixa_salarial_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_2022

Faixa salarial     %
0     de R$ 4.001/mês a R$ 6.000/mês  27.6
1    de R$ 8.001/mês a R$ 12.000/mês  22.0
2     de R$ 6.001/mês a R$ 8.000/mês  18.7
3     de R$ 3.001/mês a R$ 4.000/mês  13.3
4   de R$ 12.001/mês a R$ 16.000/mês   7.3
5     de R$ 2.001/mês a R$ 3.000/mês   5.6
6   de R$ 16.001/mês a R$ 20.000/mês   2.0
7     de R$ 1.001/mês a R$ 2.000/mês   1.2
8   de R$ 30.001/mês a R$ 40.000/mês   1.0
9   de R$ 20.001/mês a R$ 25.000/mês   0.6
10  de R$ 25.001/mês a R$ 30.000/mês   0.4
11             Menos de R$ 1.000/mês   0.2
12            Acima de R$ 40.001/mês   0.2

In [399]:
f.grafico_barras(freq_faixa_salarial_2022,'Faixa salarial',
                 'Faixa salarial das pessoas Analistas de dados em 2022','cores_uma_barra',13)

##### <font color= MediumSpringGreen> Faixa salarial Sênior </font>

In [409]:
len(senior_2022)

146

In [406]:
freq_faixa_salarial_senior_2022 = f.tabela_frequencia(senior_2022,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_senior_2022

Faixa salarial     %
0   de R$ 8.001/mês a R$ 12.000/mês  43.8
1  de R$ 12.001/mês a R$ 16.000/mês  21.2
2    de R$ 6.001/mês a R$ 8.000/mês  17.1
3  de R$ 16.001/mês a R$ 20.000/mês   6.8
4    de R$ 4.001/mês a R$ 6.000/mês   5.5
5  de R$ 30.001/mês a R$ 40.000/mês   3.4
6  de R$ 25.001/mês a R$ 30.000/mês   0.7
7            Acima de R$ 40.001/mês   0.7
8  de R$ 20.001/mês a R$ 25.000/mês   0.7

In [408]:
f.grafico_barras(freq_faixa_salarial_senior_2022,'Faixa salarial',
                 'Faixa salarial das pessoas Analistas de dados Sênior em 2022','cores_uma_barra',9)

##### <font color= MediumSpringGreen> Faixa salarial Pleno </font>

In [410]:
len(pleno_2022)

201

In [412]:
freq_faixa_salarial_pleno_2022 = f.tabela_frequencia(pleno_2022,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_pleno_2022

Faixa salarial     %
0    de R$ 4.001/mês a R$ 6.000/mês  33.8
1    de R$ 6.001/mês a R$ 8.000/mês  29.4
2   de R$ 8.001/mês a R$ 12.000/mês  22.9
3    de R$ 3.001/mês a R$ 4.000/mês   7.5
4  de R$ 12.001/mês a R$ 16.000/mês   3.0
5    de R$ 2.001/mês a R$ 3.000/mês   1.5
6  de R$ 20.001/mês a R$ 25.000/mês   1.0
7  de R$ 25.001/mês a R$ 30.000/mês   0.5
8    de R$ 1.001/mês a R$ 2.000/mês   0.5

In [417]:
f.grafico_barras(freq_faixa_salarial_pleno_2022,'Faixa salarial',
                 'Faixa salarial das pessoas Analistas de dados Pleno em 2022','cores_tres_barras',9)

##### <font color= MediumSpringGreen> Faixa salarial Júnior </font>

In [411]:
len(junior_2022)

157

In [418]:
freq_faixa_salarial_junior_2022 = f.tabela_frequencia(junior_2022,"('P2_h ', 'Faixa salarial')")
freq_faixa_salarial_junior_2022

Faixa salarial     %
0   de R$ 4.001/mês a R$ 6.000/mês  40.1
1   de R$ 3.001/mês a R$ 4.000/mês  33.1
2   de R$ 2.001/mês a R$ 3.000/mês  15.9
3   de R$ 6.001/mês a R$ 8.000/mês   6.4
4   de R$ 1.001/mês a R$ 2.000/mês   3.2
5            Menos de R$ 1.000/mês   0.6
6  de R$ 8.001/mês a R$ 12.000/mês   0.6

In [421]:
f.grafico_barras(freq_faixa_salarial_junior_2022,'Faixa salarial',
                 'Faixa salarial das pessoas Analistas de dados Júnior em 2022','cores_duas_barras',7)

#### <font color= MediumSpringGreen> Tempo de experiência </font>

In [427]:
freq_tempo_experiencia_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,
                    "('P2_j ', 'Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?')")
freq_tempo_experiencia_2022

Quanto tempo de experiência na área de TI/Engenharia de Software você teve antes de começar a trabalhar na área de dados?  \
0  Não tive experiência na área de TI/Engenharia ...                                                                          
1                                     Menos de 1 ano                                                                          
2                                      de 1 a 2 anos                                                                          
3                                      de 3 a 4 anos                                                                          
4                                     de 7 a 10 anos                                                                          
5                                    Mais de 10 anos                                                                          
6                                      de 5 a 6 anos                                                                          

      %  
0  52.8  
1  21.6  
2  10.9  
3   5.6  
4   3.8  
5   3.6  
6   1.8

In [432]:
f.grafico_barras(freq_tempo_experiencia_2022,'Tempo de experiência',
                 'Tempo de experiência em TI das pessoas Analistas de dados em 2022 ','cores_uma_barra',7)

Mais da metade dos profissionais não tiveram uma experiência na área de tecnologia antes de atuar no cargo.

In [431]:
freq_tempo_experiencia_dados_2022 = f.tabela_frequencia(df_analista_dados_2022_puro,
                                                        "('P2_i ', 'Quanto tempo de experiência na área de dados você tem?')")
freq_tempo_experiencia_dados_2022

Quanto tempo de experiência na área de dados você tem?     %
0                                      de 1 a 2 anos      35.9
1                                      de 3 a 4 anos      23.0
2                                     Menos de 1 ano      17.3
3                                      de 4 a 6 anos      12.7
4                                     de 7 a 10 anos       7.1
5                                    Mais de 10 anos       4.0

In [434]:
f.grafico_barras(freq_tempo_experiencia_dados_2022,'Tempo de experiência em dados',
                 'Tempo de experiência em Dados das pessoas Analistas de dados em 2022 ','cores_tres_barras',7)

#### <font color= MediumSpringGreen> Ferramentas </font>

##### <font color= MediumSpringGreen> **Quais das fontes de dados listadas você já analisou ou processou no trabalho?** </font>

In [435]:
freq_fontes_processadas_2022 = f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,
                                                                             [11,12,13,14,15,16,17,18],
                                                                             'fontes_dados')

freq_fontes_processadas_2022

fontes_dados     %
0                                       Planilhas  30.6
1  Dados relacionais (estruturados em bancos SQL)  29.4
2                               Textos/Documentos  16.3
3                          Dados georeferenciados  10.9
4               Dados armazenados em bancos NoSQL   9.1
5                                         Imagens   2.6
6                                          Áudios   0.7
7                                          Vídeos   0.4

In [436]:
f.grafico_barras(freq_fontes_processadas_2022,'Fontes de dados processadas',
                 'Fontes de dados processadas pelas pessoas Analistas de dados em 2022 ','cores_duas_barras',8)

##### <font color= MediumSpringGreen> **Entre as fontes de dados listadas, quais você utiliza na maior parte do tempo?** </font>

In [437]:
freq_fontes_mais_utilizadas_2022 = f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,
                                                                        [20,21,22,23,24,25,26,27],
                                                                        'fontes_dados_mais_utilizadas')
freq_fontes_mais_utilizadas_2022

fontes_dados_mais_utilizadas     %
0  Dados relacionais (estruturados em bancos SQL)  50.1
1                                       Planilhas  40.5
2               Dados armazenados em bancos NoSQL   4.4
3                               Textos/Documentos   3.6
4                          Dados georeferenciados   1.2
5                                          Vídeos   0.1
6                                          Áudios   0.1
7                                         Imagens   0.0

In [441]:
f.grafico_barras(freq_fontes_mais_utilizadas_2022,'Fontes de dados mais utilizadas',
                 'Fontes de dados mais utilizadas pelas pessoas Analistas de dados em 2022 ','cores_duas_barras',7)

##### <font color= MediumSpringGreen> **Quais das linguagens listadas abaixo você utiliza no trabalho?**
 </font>

In [439]:
freq_linguagens_2022 = f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,
                                                                [29,30,31,32,33,34,35,36,37,38,39,40,41,42],
                                                                'linguagens_mais_utilizadas')

freq_linguagens_2022

linguagens_mais_utilizadas     %
0                             SQL  43.5
1                          Python  33.7
2                              R    7.3
3                Visual Basic/VBA   5.1
4                       SAS/Stata   3.5
5                            Java   2.2
6   Não utilizo nenhuma linguagem   2.0
7                      Javascript   1.4
8                        C/C++/C#   0.5
9                           Scala   0.4
10                         Matlab   0.3
11                          Julia   0.1
12                            PHP   0.1
13                           .NET   0.0

In [440]:
f.grafico_barras(freq_linguagens_2022,'Linguagens utilizadas',
                 'Linguagens utilizadas pelas pessoas Analistas de dados em 2022 ','cores_duas_barras',13)

##### <font color= MediumSpringGreen> **Quais dos bancos de dados/fontes de dados listados abaixo você utiliza no trabalho?**
 </font>

In [442]:
freq_SGBD_2022 = f.percentual_colunas_multiplas_respostas(df_analista_dados_2022,
                                         [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
                                            61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
                                         'linguagens_mais_utilizadas')

freq_SGBD_2022

linguagens_mais_utilizadas     %
0                  SQL SERVER  12.2
1             Google BigQuery  11.7
2                  PostgreSQL  10.6
3                       MySQL  10.6
4                  Databricks   8.0
5                          S3   6.9
6                      Oracle   6.3
7             Amazon Redshift   5.3
8               Amazon Athena   4.3
9                   Snowflake   3.8
10                    MongoDB   3.8
11                   SAP HANA   2.2
12                     Presto   1.9
13                       Hive   1.9
14           Microsoft Access   1.7
15       Amazon Aurora ou RDS   1.4
16                   Firebase   1.2
17                    MariaDB   1.2
18              ElasticSearch   1.2
19                        DB2   0.9
20                     SQLite   0.9
21                   Firebird   0.4
22                   DynamoDB   0.4
23           Google Firestore   0.3
24                      Neo4J   0.2
25                  Cassandra   0.2
26                     Splunk   0.2
27                      HBase   0.1
28                     Sybase   0.1
29                      Redis   0.1
30                    Datomic   0.1
31                    Vertica   0.0
32                    CoachDB   0.0

In [448]:
f.grafico_barras(freq_SGBD_2022,"SGBD's utilizados",
                 "Top 5: SGBD's utilizados pelas pessoas Analistas de dados em 2022",'cores_duas_barras',10)

# -> CONTINUAR

##### <font color= MediumSpringGreen> **Quais das opções de Cloud listadas abaixo você utiliza no trabalho?**
 </font>

In [ ]:
f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,[78,79,80],'cloud')

cloud     %
0  Amazon Web Services (AWS)  49.3
1         Google Cloud (GCP)  29.7
2          Azure (Microsoft)  21.0

##### <font color= MediumSpringGreen> **Quais as Ferramentas de Business Intelligence você utiliza no trabalho?**
 </font>

In [ ]:
quantidade_total_respostas = len(df_state_of_data_2022)

respostas_nulas_ferramentas_BI = df_state_of_data_2022["('P4_i ', 'Microsoft PowerBI')"].isna().sum() #A coluna que indicava ferramentas de BI, foi nomeada incorretamente.
percentual_respostas_nulas_ferramentas_BI = round(respostas_nulas_ferramentas_BI/quantidade_total_respostas,3)*100

quantidade_total_respostas_analista_de_dados = len(df_analista_dados_2022_puro)
respostas_nulas_ferramentas_BI_analista_de_dados = df_analista_dados_2022_puro["('P4_i ', 'Microsoft PowerBI')"].isna().sum()
percentual_respostas_nulas_faixa_salarial_analista_de_dados = round(respostas_nulas_ferramentas_BI_analista_de_dados/quantidade_total_respostas,3)*100

quantidade_respostas_validas_analista_dados = (quantidade_total_respostas_analista_de_dados - respostas_nulas_ferramentas_BI_analista_de_dados)
percentual_quantidade_respostas_validas_analista_dados = round(quantidade_respostas_validas_analista_dados / quantidade_total_respostas_analista_de_dados,3) *100
print(
    f''' 
    Do total de {quantidade_total_respostas} (de todo o conjunto de dados da pesquisa), houveram {respostas_nulas_ferramentas_BI} ({percentual_respostas_nulas_ferramentas_BI:.2f}%) respostas nulas para escolha de ferramentas de BI.\n
    Do total de {quantidade_total_respostas_analista_de_dados} (do conjunto de dados filtrado com cargo de Analista de Dados),\n    houveram {respostas_nulas_ferramentas_BI_analista_de_dados} ({percentual_respostas_nulas_faixa_salarial_analista_de_dados:.2f}% do total de toda a pesquisa) respostas nulas para faixa salarial.
    
    Restando apenas {quantidade_respostas_validas_analista_dados} respostas válidas, cerca de {percentual_quantidade_respostas_validas_analista_dados:.2f}%.
    
    Por este motivo, não será considerado essa métrica na análise deste ano.
    '''
    )

 
    Do total de 4270 (de todo o conjunto de dados da pesquisa), houveram 4068 (95.30%) respostas nulas para escolha de ferramentas de BI.

    Do total de 504 (do conjunto de dados filtrado com cargo de Analista de Dados),
    houveram 472 (11.10% do total de toda a pesquisa) respostas nulas para faixa salarial.
    
    Restando apenas 32 respostas válidas, cerca de 6.30%.
    
    Por este motivo, não será considerado essa métrica na análise deste ano.
    


##### <font color= MediumSpringGreen> **Quais as ferramentas/tecnologias de ETL que você utiliza no trabalho como Data Analyst?**
 </font>

In [ ]:
f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,
                                                  [117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
                                                   130, 131, 132, 133, 134, 135, 136],
                                                  'sofware_ETL')

sofware_ETL     %
0                  SQL & Stored Procedures  27.1
1                           Scripts Python  26.6
2           Não utilizo ferramentas de ETL  10.5
3                               Databricks   9.9
4                           Apache Airflow   5.7
5   SQL Server Integration Services (SSIS)   4.3
6                                  Pentaho   3.0
7                                    Knime   1.9
8                     SAS Data Integration   1.9
9                                 AWS Glue   1.8
10                              Qlik Sense   1.8
11                                 Alteryx   1.7
12                         Google Dataflow   1.6
13                              SAP BW ETL   0.8
14                                  Stitch   0.6
15                                Fivetran   0.4
16                                  Talend   0.2
17                                   Luigi   0.1
18                           IBM DataStage   0.1
19                  Oracle Data Integrator   0.1

##### <font color= MediumSpringGreen> **Sua empresa utiliza alguma das ferramentas listadas para dar mais autonomia em análise de dados para as áreas de negócio?**
 </font>

In [ ]:
df_analista_dados_2022_puro.iloc[:,[138,139,140,141,142,143]]

('P7_c_1 ', 'Ferramentas de AutoML como H2O.ai, Data Robot, BigML etc.')  \
19                                                  0.0                          
30                                                  0.0                          
57                                                  0.0                          
66                                                  0.0                          
67                                                  0.0                          
...                                                 ...                          
4243                                                0.0                          
4244                                                0.0                          
4245                                                0.0                          
4266                                                0.0                          
4270                                                0.0                          

      ('P7_c_2 ', '""Point and Click"" Analytics como Alteryx, Knime, Rapidminer etc.')  \
19                                                  0.0                                   
30                                                  0.0                                   
57                                                  0.0                                   
66                                                  0.0                                   
67                                                  0.0                                   
...                                                 ...                                   
4243                                                0.0                                   
4244                                                1.0                                   
4245                                                1.0                                   
4266                                                0.0                                   
4270                                                0.0                                   

      ('P7_c_3 ', 'Product metricts & Insights como Mixpanel, Amplitude, Adobe Analytics.')  \
19                                                  0.0                                       
30                                                  0.0                                       
57                                                  0.0                                       
66                                                  0.0                                       
67                                                  0.0                                       
...                                                 ...                                       
4243                                                0.0                                       
4244                                                1.0                                       
4245                                                0.0                                       
4266                                                0.0                                       
4270                                                0.0                                       

      ('P7_c_4 ', 'Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.')  \
19                                                  1.0                                                                             
30                                                  0.0                                                                             
57                                                  1.0                                                                             
66                                                  0.0                                                                             
67                                                  0.0                                                                   

In [ ]:
f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,[138,139,140,141,142,143],'sofware_ETL')

sofware_ETL     %
0       Minha empresa não utiliza essas ferramentas.  38.5
1                                  Não sei informar.  24.8
2  Ferramentas de análise dentro de ferramentas d...  16.6
3          Product metricts & Insights como Mixpanel  10.5
4         ""Point and Click"" Analytics como Alteryx   6.6
5                  Ferramentas de AutoML como H2O.ai   3.0

In [ ]:
freq_software_otimizacao = f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,[138,139,140,141,142,143],
                                                                  'software')

#Ajuste para deixar a informação mais objetiva
freq_software_otimizacao['software'] = freq_software_otimizacao['software'].replace('Ferramentas de análise dentro de ferramentas de CRM como Salesforce Einstein Anaytics ou Zendesk dashboards.',
                                             'Salesforce Einstein Anaytics ou Zendesk dashboards.')
freq_software_otimizacao

software     %
0       Minha empresa não utiliza essas ferramentas.  38.5
1                                  Não sei informar.  24.8
2  Salesforce Einstein Anaytics ou Zendesk dashbo...  16.6
3          Product metricts & Insights como Mixpanel  10.5
4         ""Point and Click"" Analytics como Alteryx   6.6
5                  Ferramentas de AutoML como H2O.ai   3.0

#### <font color= MediumSpringGreen> Rotina de trabalho </font>

##### <font color= MediumSpringGreen> **Quais das opções abaixo fazem parte da sua rotina no trabalho atual com análise de dados?**
 </font>

In [ ]:
f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,[106,107,108,109,110,111,112,113,114,115],
                                                     'rotina')

rotina     %
0  Realizo construções de dashboards em ferrament...  22.3
1  Crio consultas através da linguagem SQL para e...  21.4
2  Processo e analiso dados utilizando linguagens...  15.7
3  Desenvolvo/cuido da manutenção de planilhas pa...  11.9
4  Realizo experimentos e estudos utilizando meto...   7.1
5                        Atuo na modelagem dos dados   6.9
6                                        Utilizo API   6.8
7              Desenvolvo/cuido da manutenção de ETL   5.9
8  Utilizo ferramentas avançadas de estatística c...   1.9
9  Nenhuma das opções listadas refletem meu dia a...   0.1

##### <font color= MediumSpringGreen> **Em qual das opções abaixo você gasta a maior parte do seu tempo de trabalho?**
 </font>

In [ ]:
f.percentual_colunas_multiplas_respostas(df_analista_dados_2022_puro,[145,146,147,148,149,150,151,152,153,154],
                                                     'rotina')

rotina     %
0  Criando consultas através da linguagem SQL par...  30.0
1  Realizando construções de dashboards em ferram...  28.4
2  Processando e analisando dados utilizando ling...  19.7
3  Desenvolvendo/cuidando da manutenção de planil...   9.5
4                     Atuando na modelagem dos dados   3.8
5  Realizando experimentos e estudos utilizando m...   3.2
6        Desenvolvendo/cuidando da manutenção de ETL   2.8
7                                     Utilizando API   1.3
8  Utilizando ferramentas avançadas de estatístic...   0.9
9  Nenhuma das opções listadas refletem meu dia a...   0.5

# <font color= MediumSpringGreen> Compilação da pesquisa </font>

# <font color= MediumSpringGreen> Considerações finais </font>